### ISSUE TITLE
live demo page is not working

### ISSUE THREAD

**Issue by guybartal** [Microsoft/PowerBI-JavaScript#109]
you have got CORS problem in demo page:

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://microsoft.github.io' is therefore not allowed access. The response had HTTP status code 403. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by noanu** [comment]
@guybartal , thanks, we are aware and investigating.

**Comment by ali-hamud** [comment]
Done. server was down.
