### ISSUE TITLE
Visual Filter

### ISSUE THREAD

**Issue by diptesh912** [Microsoft/PowerBI-JavaScript#116]
Is there anyway I can set visual Filter in TIle?

**Comment by ali-hamud** [comment]
Not Yet.

**Comment by zhll2046** [comment]
Any ETA? I see the visual filter on roadmap from this link
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Understanding-the-object-hierarchy

**Comment by ali-hamud** [comment]
Sorry. No ETA.

**Comment by ali-hamud** [comment]
This feature is available now. closing the issue.
