### ISSUE TITLE
Apply same filters multiple times and Power BI does not query back-end data

### ISSUE THREAD

**Issue by sheldonyss** [Microsoft/PowerBI-JavaScript#118]
## Background:
I am using Power BI Javascript SDK and On-Premise data gateway to integrate reports with my web application.
In one report, the back-end data (SQL Server) is constantly changing approximately every 10 seconds.
Initially, the report loaded with correct data is displayed.

## Symptom:
Power BI service did not query data from data source if the filters send to Power BI service are the same, despite the fact that data had changed in data source.

## Stesps:
1. Load report for the first time with default filter values and the report is displayed with latest data from SQL server.
![image](https://cloud.githubusercontent.com/assets/15058152/21125559/9d91f240-c121-11e6-981b-68932dd956d4.png)

2. Wait for data change in back-end, and apply filter again. It seems that Power BI services ignored the filters and the report data is not refreshed.
![image](https://cloud.githubusercontent.com/assets/15058152/21125677/4bf52db6-c122-11e6-8f80-cd22f4b40f84.png)

3. Change the filter and apply filter. Report is refreshed with latest data.

## Note:
From my browser console window, I can clearly see the filter schema. And i can confirm that I have called the setFilter API on report page object. 
![image](https://cloud.githubusercontent.com/assets/15058152/21125774/f2d2ef92-c122-11e6-9f91-8b7f1fd81022.png)

Looks like that Power BI service has its own logic to determine when to query data from data source and ignored my filters.

**Comment by ali-hamud** [comment]
This is by design. setFilters only changes the filter pane, it doesn't fetch the data again.
what you need is a refresh functionality. we will publish refresh functionality once we define the payments.
Thanks.

**Comment by ali-hamud** [comment]
refresh is available now in version 2.3.0

usage: report.refresh()
