### ISSUE TITLE
UML relationships directions are reversed

### ISSUE THREAD

**Issue by IcarusSO** [Microsoft/PowerBI-JavaScript#119]
The direction of the UML relations are wrong.
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Understanding-the-object-hierarchy

**Comment by ali-hamud** [comment]
![image](https://cloud.githubusercontent.com/assets/23071967/21133147/28e4358a-c120-11e6-92eb-957ad58b4350.png)

updated. thanks.

**Comment by IcarusSO** [comment]
Should the Page -> Visual relation be reversed?
Thanks

**Comment by ali-hamud** [comment]
sure. didn't pay attention to it.
![image](https://cloud.githubusercontent.com/assets/23071967/21133462/92d9b4a0-c121-11e6-919f-5132ad4779bb.png)
