### ISSUE TITLE
Overwrite filter

### ISSUE THREAD

**Issue by m-moris** [Microsoft/PowerBI-JavaScript#121]
I'm trying pre-applied filters. In my understanding the filters will add to filters of saved report.

https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details#options

I want to overwrite the filter of saved report. Is it possible?

**Comment by ali-hamud** [comment]
I am not sure I am understanding your questions.

you can override the report filters by using the setFilters and removeFilters methods:
[https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters)

you can also try these functionality in this tool:
[https://microsoft.github.io/PowerBI-JavaScript/demo/](https://microsoft.github.io/PowerBI-JavaScript/demo/)

let me know if you have more questions.

**Comment by noanu** [comment]
Hi,

You can also use the IReportLoadConfiguration interface to configure the filters when loading the report.
