### ISSUE TITLE
DataSelected event for Map Visual does not provide ToolTips data

### ISSUE THREAD

**Issue by JonJam** [Microsoft/PowerBI-JavaScript#126]
We have a report which contains a Map Visual displaying a number of devices across the world.

Each device has a category according to the owner. This is used as the Legend in order that the points on the map are color coded e.g. all devices owned by Company A are Red and all devices owned by Company B are Blue. The Device ID is part of the Tooltips.

We want to be able to click on one of the devices, which depending on another the category, navigates to a different report page but also applies a filter for the ID of the device clicked on.

However the detail of the Data selected event only contains the Location and Legend values, and not any of the Tooltips data.

**Comment by noanu** [comment]
Hi,

I wanted to update that the fix was checked in and should be available at production in about 2 weeks.

thanks!

**Comment by JonJam** [comment]
@noanu Thanks very much :)

**Comment by ali-hamud** [comment]
Fixed. please try
