### ISSUE TITLE
DataSelected event for Chiclet Slicer Visual does not provide Values or Image data.

### ISSUE THREAD

**Issue by JonJam** [Microsoft/PowerBI-JavaScript#127]
We have a report which contains a Chiclet Slicer Visual which is used as button to navigate to another page.

Currently the dataSelected event only returns the data contained in the Category field; not also the Values and Image fields as well.

**Comment by noanu** [comment]
Hi Jon,

We are aware of a general bug we have with the data selection event's values, and we are already working to fix it. I hope that it will be checked in soon, and than will be deployed to production a few weeks later. I will update here when we have a better time estimation.

**Comment by JonJam** [comment]
Thanks @noanu. I didn't realize it was a general bug and not visual specific.

**Comment by noanu** [comment]
Hi,

I wanted to update that the fix was check in and should be available at production in about 2 weeks.

thanks!

**Comment by ali-hamud** [comment]
Fixed. please try.
