### ISSUE TITLE
dataSelected event being fired automatically after page load

### ISSUE THREAD

**Issue by JonJam** [Microsoft/PowerBI-JavaScript#128]
In a report we are currently embedding, I have noticed that after navigating to a separate page the dataSelected is being fired automatically, not from a user interaction.

This is causing odd behavior such as when a user navigates back to a previous page, the report automatically navigates forward to the page the user has just left.

**Comment by ali-hamud** [comment]
hi @JonJam 

we could not repro this issue.
Is it solved for you?

**Comment by ali-hamud** [comment]
Closing as Not Repro.
please open if you still have this.
