### ISSUE TITLE
Enhancements Needed for Power BI Embedded

### ISSUE THREAD

**Issue by cruise-insights** [Microsoft/PowerBI-JavaScript#137]
Embedding a tile is a necessary enhancement. Also . inclusion for embedding Dashboards and making Power BI embedded mobile UX same as Power BI Mobile are of high value.

**Comment by sharonlai** [comment]
thanks cruise insights, this is acknowledged and we have it in our backlog

**Comment by ali-hamud** [comment]
Hi @cruise-insights 
Embedding tile and dashboard is already in production.
Embedding in Mobile layout is still in our backlog.

**Comment by ali-hamud** [comment]
Embedding in mobile layout is in production.
please check: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-For-Mobile

Thank you.
