### ISSUE TITLE
Get  Reports List  using powerBi.com service

### ISSUE THREAD

**Issue by elena89rossi** [Microsoft/PowerBI-JavaScript#143]
Hi all,
I use powerBi service via javascript in my application.
I retrieve AAD Access token and  i and all works well.
Now I need to retrieve my reports list,with reports name and id ( not single report as i see in documentation) but I not found any solution to do this.

Can anyone help me?

Thanks a lot,
Elena

**Comment by ali-hamud** [comment]
**we have Rest API which helps you do what you need. you can try it here:**
[http://docs.powerbi.apiary.io/#reference/report-preview](http://docs.powerbi.apiary.io/#reference/report-preview)

We also have C# nuget called Microsoft.PowerBI.Api:
[https://www.nuget.org/profiles/powerbi](https://www.nuget.org/profiles/powerbi)

and we have npm package if you write nodeJs:
https://github.com/Microsoft/PowerBI-Node

usage example in C#:
https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/blob/master/ProvisionSample/Program.cs
search GetReports

**Comment by cruise-insights** [comment]
@ali-hamud 

We have done the automation of this flow using Power BI Node JS SDK

Any way I could help?

Thanks

**Comment by sharonlai** [comment]
@cruise-insights, how would you compare PowerShell tools to automate it all, relative to NodeJS?

**Comment by elena89rossi** [comment]
I've used the  Rest API  and all works well.
Thanks,
Elena

**Comment by cruise-insights** [comment]
@sharonlai 

Both cases would have to be run server side,since it makes the code, device-independent

In our case Node JS SDK was preferable , so that we could manage error callbacks.

The only problem using Node JS SDK is code browsing. (I was unable to find a detailed functional documentation).


Thanks

**Comment by sharonlai** [comment]
thanks for the feedback.

**Comment by ali-hamud** [comment]
@cruise-insights 
please feel free to contribute to our Documentation in https://github.com/Microsoft/PowerBI-Node or https://github.com/Microsoft/PowerBI-Cli.

If you do, please open a pull request and I will look into it.

Thank you,
Ali Hamud

**Comment by cruise-insights** [comment]
@ali-hamud 
Sure I will share a documentation I made.
Also  if I could contribute to building delete workspace api.

Thanks,
