### ISSUE TITLE
IFrame creation not compatible with Content Security Policy best practices.

### ISSUE THREAD

**Issue by vangorra** [Microsoft/PowerBI-JavaScript#151]
When Content-Security-Policy (CSP) is enabled, the creation of the iframe is using generated inline css. This behavior is explicitly denied when CSP is enabled.

https://github.com/Microsoft/PowerBI-JavaScript/blob/7e25b4b363c662b90b2810c46e01ffafda1b5004/src/embed.ts#L140

Perhaps using document.createElemenent and setting the styles that way would work better?

**Comment by ali-hamud** [comment]
Thank you for opening this issue. we will handle it.

**Comment by vangorra** [comment]
While not directly this project's responsibility, you should also be made aware that powerbi-models depends on JESN which makes use of a lot of unsafe-eval to operate. In order for this project to CSP safe, powerbi-models will have to make some changes too.

Related issue:
https://github.com/Microsoft/powerbi-models/issues/48

**Comment by ali-hamud** [comment]
We will look into PowerBI-Models later. issue is opened there.
Thank you.
