### ISSUE TITLE
Is there way to add Toggle functionality between pages based on setInterval eg every 10 seconds?

### ISSUE THREAD

**Issue by dhawalc** [Microsoft/PowerBI-JavaScript#157]
I'm trying to create a Report based presentation mode where if there are 3 pages in a report, I can add keep it open and basically just toggle between the pages every 5 seconds. Please let me know if this is possible.

**Comment by fume** [comment]
What do you mean with "keep it open"?

If you want to change page every 5 seconds, you can. Just handle the reportloaded event, then do a getPages. Then, is just up to you how to change page. A setInterval should be fine, just call a function every 5 seconds that set the current page to the next one (or the first one if you reached the end). You can set the current page calling the setActive() method on a page instance (returned from the getPages() method).

I guess that something like this should work:

```javascript
var reportPages;
var currentPageIndex = 0;
report.on('loaded', function(event)
{
    report.getPages().then(function(pages)
    {
        reportPages = pages;
        setInterval(function(){
              if(currentPageIndex>=reportPages.length-1)
                      currentPageIndex = -1;
              reportPages[currentPageIndex+1].setActive();
              currentPageIndex++;
        }, 5000);
    });    
});
```

Regards, FM

**Comment by ali-hamud** [comment]
please re-open if you want more help.
