### ISSUE TITLE
Reports stopped working

### ISSUE THREAD

**Issue by rashigoyal03** [Microsoft/PowerBI-JavaScript#168]
Hi,

Suddenly my all power bi reports stopped working. Showing me these errors
https://microsoft.github.io/PowerBI-JavaScript/demo/bower_components/es6-promise/es6-promise.js
https://microsoft.github.io/PowerBI-JavaScript/demo/bower_components/powerbi-client/dist/powerbi.js
 https://microsoft.github.io/PowerBI-JavaScript/demo/bower_components/fetch/fetch.js
https://microsoft.github.io/PowerBI-JavaScript/demo/bower_components/powerbi-client/dist/powerbi.js

Please help its very urgent.

**Comment by ali-hamud** [comment]
please clear your cache and try again.
We replaced the use of the bower_components with npm packages in live demo.
