### ISSUE TITLE
powerbi.embed() raises an error when using minified js

### ISSUE THREAD

**Issue by kazup0n** [Microsoft/PowerBI-JavaScript#17]
When using minified js file (`powerbi.min.js`),  `powerbi.embed( elm, { options ..})` throws an error described below.

The names of components have been shorten, so searching matched components will fail.

https://github.com/Microsoft/PowerBI-JavaScript/blob/master/src/core.ts#L109

Here is my stacktrace.

```
powerbi.js:118 Uncaught (in promise) Error: Attempted to embed component of type: report but did not find any matching component.  Please verify the type you specified is intended.(…)

   e.embedNew @ powerbi.js:118
   e.embed @ powerbi.js:100
   renderReport @ app.bundle.js:30105
   report @ app.bundle.js:29966
   combination @ app.bundle.js:29540dispatch @ app.bundle.js:29141
   (anonymous function) @ app.bundle.js:29870
   dispatch @ app.bundle.js:29687
   (anonymous function) @ app.bundle.js:30080
```

**Comment by mattmazzola** [comment]
I would be interested to see the minified file to understand what happened.
Minification should not change strings and we have it set here:

https://github.com/Microsoft/PowerBI-JavaScript/blob/master/src/report.ts#L8
`static name = "Report";`

I have ran into other errors in newer browsers which say `name` is a readonly property and cannot be assigned so I am planning to avoid this collision with `function.name` and change this variable to `type`

**Comment by kazup0n** [comment]
As @mattmazzola says, This is because of  ES6's [Function.name](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/name)  and the side effect of minifying.

**Comment by mattmazzola** [comment]
This was fixed in the dev branch: https://github.com/Microsoft/PowerBI-JavaScript/commit/a0c9d767e196e957d45db6d324473c1d5f85c6ed

**Comment by wbreza** [comment]
@mattmazzola Let's move this over to the master branch as well.

**Comment by kenhowardpdx** [comment]
@mattmazzola @wbreza Any movement on this?

**Comment by mattmazzola** [comment]
The 2.0.0 release was published and includes the fix.
