### ISSUE TITLE
Visualizations pane does not appear in Edit mode unless filterPaneEnabled is true

### ISSUE THREAD

**Issue by t-val** [Microsoft/PowerBI-JavaScript#170]
If filterPaneEnabled is false and you load a report in Edit mode, the Visualizations pane does not appear.  The Fields pane does appear.  Seems like a bug to me.

**Comment by ali-hamud** [comment]
We were able to reproduce this bug.
I will update later.

**Comment by ali-hamud** [comment]
Visualization pane without filters are useful but not that useful.
We are marking this issue as “Won’t Fix”.

please let me know if you think otherwise.

**Comment by GraemeSMiller** [comment]
This is surely a bug? Why should I need to display filters to see Visualisations?

**Comment by ali-hamud** [comment]
I agree that this is a bug. but we are busy with other features.
Can you please explain why this is important, so we could give it higher priority?
