### ISSUE TITLE
Basic Filter limitation or BUG?

### ISSUE THREAD

**Issue by zhll2046** [Microsoft/PowerBI-JavaScript#171]
`const basicFilter: pbi.models.IBasicFilter = {

$schema: "http://powerbi.com/product/schema#basic",

target: {

table: "Store",

column: "Count"

},

operator: "In",

values: [1,2,3,4] // Is there any limit on the number of values here?

}`

Based on my test, the report embeded can be loaded but the tiles show "can't display the visual" when the values contains too many values(maybe 1000 or more).

**Comment by ali-hamud** [comment]
Actually I didn't try it. I will try it.
Why do you have so much values to filter on?
I recommend you to try AdvancedFilter or BasicFilter with NotIn operator.

**Comment by noanu** [comment]
Hi @zhll2046 
PowerBI limits the number of values that can be filtered to 500. I also recommend to try AdvancedFilter (filter by range) or BasicFilter with NotIn operator as Ali proposed.

**Comment by zhll2046** [comment]
Thanks both

**Comment by zhll2046** [comment]
@noanu 
@ali-hamud 
How to use the range in a advanced filter? with a Between key word of what? I don't see it in the wiki,
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters

It would appreciated if you could share any more detailed documentation on PBI JS API

**Comment by noanu** [comment]
Hi @zhll2046 
Please look at this gitHub: https://github.com/Microsoft/powerbi-models, specifically in models.ts file.
You will find there the definitions for the filters' classes that powerBI-JavaScript expects to receive in setFilters method.

**Comment by ali-hamud** [comment]
@zhll2046
I am closing this issue. please re-open if you have more questions.
