### ISSUE TITLE
Unable to save the report

### ISSUE THREAD

**Issue by remeezp** [Microsoft/PowerBI-JavaScript#185]
Hi,

I am unable to save a report.

Error message:

> Something went wrong
> Unable to save the report
> Please verify you have the right permissions or contact support. If you contact support, please provide these details.
> Show technical detailsGet help

My config permissions are set to 7 (All).  Also in these are the scopes I am sending

`const scopes = ['Dataset.Read','Workspace.Report.Create', 'Workspace.Report.SaveAs', 'Workspace.Report.Save'];`

The following error is from chrome developer tools window:

> POST https://wabi-uk-south-redirect.analysis.windows.net/appTokenEmbed/explorations/savereport/605766 401 (Unauthorized)

**Comment by noanu** [comment]
Hi @remeezp 
You are not using the correct scopes - you are missing Report.ReadWrite (and Save/SaveAs that you used are wrong).
You can find documnetation for the scopes here: https://docs.microsoft.com/en-us/azure/power-bi-embedded/power-bi-embedded-app-token-flow

**Comment by remeezp** [comment]
Thanks
