### ISSUE TITLE
Dashboard drillthrough to Report

### ISSUE THREAD

**Issue by t-val** [Microsoft/PowerBI-JavaScript#187]
Any chance that clicking a dashboard tile to drillthough to a report, like app.powerbi.com does, will ever be possible?  I'm not sure how this could be achieved, but it's the biggest complaint we get about our custom app.  I guess we would need some sort of onTileClicked method in a dashboard that would return the report GUID that the tile is sourced from.  Then we could just call a new embed routine but as a report instead of a dashboard.

If anyone else has any ideas of how this could be made possible, please share.

**Comment by noanu** [comment]
Hi @t-val 
Good news! We have this event already.
Please see example here: https://github.com/Microsoft/PowerBI-Developer-Samples/blob/master/PowerBI.com%20Integrate/integrate-dashboard-web-app/PBIWebApp/Site.Master

 (look for "tileClicked" in this file to get to the relevant code)
