### ISSUE TITLE
Need to know when data is unselected

### ISSUE THREAD

**Issue by fulky** [Microsoft/PowerBI-JavaScript#188]
dataSelected works well but how would I detect when items are unselected or cleared?  dataSelected does not fire when you click off the selections on the visualization.   I need to know when selections are cleared.

**Comment by noanu** [comment]
Hi @fulky 
We will discuss this requirement and see if we can add it to our backlog. I will comment here when I have updates.
Thanks.

**Comment by mfatica** [comment]
This is a big request from our side as well

**Comment by noanu** [comment]
Hi @mfatica thanks for commenting, I will update here when we have a decision/ETA for this request.
(I think that I deleted you comment by mistake - sorry..).

**Comment by noanu** [comment]
Hi,

We added a code that returns an empty array of dataPoints when deselecting a data point. It should get to production in ~3 weeks. 
I am closing this issue, please reopen if it doesn't work for you.
