### ISSUE TITLE
[Embedded] Replace web url

### ISSUE THREAD

**Issue by dawcza3** [Microsoft/PowerBI-JavaScript#189]
Is there any way to set web url for specific table in raport from power bi workspace?

**Comment by noanu** [comment]
Hi @dawcza3 
This isn't possible now, however you can use tile embed - create a dashboard with this table and embed this specific tile. See documentation for tile embed here: https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-tile/
