### ISSUE TITLE
CSP Compatibility error

### ISSUE THREAD

**Issue by jsturtevant** [Microsoft/PowerBI-JavaScript#190]
I am using PowerBI Embedded from a Sales Force Lightning Component.  [SalesForce is enabling the LockerService](https://developer.salesforce.com/blogs/developer-relations/2017/02/lockerservice-lightning-container-third-party-libraries-lightning-components.html) later this year which requires components to be CSP Compatible.  When the locker service is disabled PowerBi version 2.3 loads and the reports are displayed.  But when the locker service is enabled it does not load (iframe is not displayed at all).

I found the CSP Compatible version under releases [here](https://github.com/Microsoft/PowerBI-JavaScript/releases/tag/closed-t-naabus%2FiFrameCSPCompatible).  This got us further, the iframe partially loads and displays the pulsing bar PowerBI icon but then errors out with the following:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' chrome-extension: 'unsafe-inline' https://sfdc.azureedge.net *.na35.visual.force.com https://ssl.gstatic.com/accessibility/". throws at /resource/1491422854000/PowerBIJSFull:2958:27
```

Any ideas on how to resolve the issue?  Currently disabling LockerService works but will need to have a fix when the LockerService becomes mandatory in a few months.

**Comment by ali-hamud** [comment]
related issue:
https://github.com/Microsoft/powerbi-models/issues/48

**Comment by ali-hamud** [comment]
Hi @jsturtevant 

Update: we started to fix this issue.
ETA: 2nd - 3rd week of October.

**Comment by aviindore** [comment]
I have disable the CSP services  in salesforce and tried after that to use the iframe in lightening but still it not taking the authentication process.
I have checked all the method to call the authentication process, but its seems like not supporting in lightning . Is this known issue ?

**Comment by ali-hamud** [comment]
Hi,

Just an update: issue have been solved and deployed. please re-check.

Hi @aviindore 
I am not familiar with lightening component, but we fixed this issue, so you can try and see if it's related.
