### ISSUE TITLE
nuget/bower

### ISSUE THREAD

**Issue by grahamehorner** [Microsoft/PowerBI-JavaScript#191]
please create public nuget/bower packages for the installation of the javascript into projects; VS2015/VS2017/VSCODE aren't able to see any power bi packages using nugget/bower ?

**Comment by ali-hamud** [comment]
we already have.
[https://www.nuget.org/packages/Microsoft.PowerBI.JavaScript/](https://www.nuget.org/packages/Microsoft.PowerBI.JavaScript/)

Thanks.
