### ISSUE TITLE
Embed report from workspace other than "My Workspace"

### ISSUE THREAD

**Issue by riteshbhoi** [Microsoft/PowerBI-JavaScript#192]
I don't see any configuration to specify workspace or group, if the report is located in a different workspace other than "My Workspace".

**Comment by noanu** [comment]
Hi @riteshbhoi 
You should add groupId=<groupId> to your embed url.
Example:
https://app.powerbi.com/reportEmbed?reportId=<reportId>&groupId=<groupId>
