### ISSUE TITLE
Getting 401 when report is rendered.

### ISSUE THREAD

**Issue by riteshbhoi** [Microsoft/PowerBI-JavaScript#193]
I am able to embed report, but get below 401 error in console. Not sure if i am missing anything.

HTTP401: DENIED - The requested resource requires user authentication.
(XHR)POST - https://df-msit-scus.analysis.windows.net/explore/explorations/1478022/cache

I am using Microsoft Edge 40.15063.0.0, powerbi-client v2.3.0

**Comment by noanu** [comment]
Hi @riteshbhoi 

Could you please provide the activityId and requestId of the request so that we can investigate?

**Comment by riteshbhoi** [comment]
Below are the details.
ActivityId: b570fd16-15c2-4844-a8b4-8c65e76db4a2
RequestId: 1c2eacf9-f639-d6a5-9c2b-4535a0b8263b

**Comment by varund29** [comment]
I am also getting same error,

   ActivityId: 0e8c0b1d-92e9-4ceb-b7e4-9f58b1b99350
   RequestId: b24a669f-249b-64ac-4a14-20559e6b81db

Please look into issue.

**Comment by riteshbhoi** [comment]
@noanu any update on this issue?

**Comment by varund29** [comment]
Issue got resolved when i used

Origin: **https://app.powerbi.com**

instaed of

Origin: **https://msit.powerbi.com**

Needs to code as below
var embedUrl = "https://app.powerbi.com/reportEmbed?reportId=" + reportObj.ReportID
var config = {
type: 'report',
accessToken: accessToken,
embedUrl: embedUrl,
id: reportObj.ReportID,
settings: {
filterPaneEnabled: false,
navContentPaneEnabled: true
}
};

===============================

Out put is :

`Request URL: https://df-msit-scus-redirect.analysis.windows.net/explore/reports/xxxxxx-xxxxxx-xxxxx-xxxxxxx-xxxxx...
Request Method: OPTIONS
Status Code: 200 / OK
- Request Headers
Accept: */*
Accept-Encoding: gzip, deflate
Access-Control-Request-Headers: activityid, requestid, authorization, accept
Access-Control-Request-Method: GET
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 0
Host: df-msit-scus-redirect.analysis.windows.net
Origin: https://app.powerbi.com
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)`

- Response Headers
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: activityid,requestid,authorization
Access-Control-Allow-Origin: https://app.powerbi.com
Access-Control-Max-Age: 300
Content-Length: 0
Date: Mon, 08 May 2017 10:06:37 GMT
Server: Microsoft-HTTPAPI/2.0

look into 
http://stackoverflow.com/questions/43776737/page-navigation-not-happening-in-power-bi-embedded-report
https://community.powerbi.com/t5/Issues/Page-navigation-not-happening-in-embedded-report/idc-p/171360

**Comment by riteshbhoi** [comment]
For me this issue occurs even when i am not doing any page navigation (switching report pages). I am using "https://app.powerbi.com/reportEmbed" embed URL and still see 401 for Cache POST operation for "https://df-msit-scus-redirect.analysis.windows.net/explore/explorations/1478022/cache".

**Comment by varund29** [comment]
Again above error repro in our production...
`Request URL: https://df-msit-scus-redirect.analysis.windows.net/explore/explorations/1570046/cache
Request Method: POST
Status Code: 401 / Unauthorized`

- Request Headers
`Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: en-US, en; q=0.5
ActivityId: 924e5293-afe0-427b-bf24-8d332cd7da50
Authorization: Bearer xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Cache-Control: no-cache
Connection: Keep-Alive
Content-Length: 26609
Content-Type: application/json; charset=utf-8
Host: df-msit-scus-redirect.analysis.windows.net
Origin: https://app.powerbi.com
Referer: https://app.powerbi.com/reportEmbed?reportId=xxxxxx-xxxxx-xxxxx-xxxxxx-xxxx
RequestId: 7003dda8-8319-4db2-df42-806ed1b883b4
User-Agent: Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 10.0; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729)`

- Response Headers

`Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://app.powerbi.com
Cache-Control: no-store, must-revalidate, no-cache
Content-Type: application/octet-stream
Date: Tue, 16 May 2017 10:03:49 GMT
RequestId: 7003dda8-8319-4db2-df42-806ed1b883b4
Server: Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Strict-Transport-Security: max-age=31536000; includeSubDomains
Transfer-Encoding: chunked
X-Content-Type-Options: nosniff
X-Frame-Options: deny`

**Comment by ali-hamud** [comment]
I think there was something wrong in App registration.
can you please try to register your application again and try?
https://dev.powerbi.com/apps

**Comment by ali-hamud** [comment]
Do you still have this problem?

**Comment by varund29** [comment]
Now it's working fine for me, without issues.

Thanks

**Comment by ccarse** [comment]
We're now seeing this issue, do you know what fixed it @varund29?

Thanks

**Comment by kwoodcf1** [comment]
I'm getting the same problem on 
POST https://wabi-us-north-central-redirect.analysis.windows.net/explore/explorations/6109008/cache 401 (Unauthorized)

The report renders fine.

On a side note there looks to be some performance issues I'm wondering if this is related?

RequestId:fd32d5d1-7bc3-95b8-f733-d28cf1dbdb08
ActivityId:ec91e9fb-875d-4a0a-be54-7dccb29b035b

**Comment by acomito** [comment]
@kwoodcf1 same here. Getting this in the console but report renders. Filters don't seem to be working. Did you ever solve this?
