### ISSUE TITLE
Updating token using setAccessToken returns [400] NotSupported

### ISSUE THREAD

**Issue by taarskog** [Microsoft/PowerBI-JavaScript#198]
According to https://github.com/Microsoft/PowerBI-JavaScript/wiki/Update-Embed-Token it should be possible to update an access token that is near expiry **without** reloading the embedded report.

However when I try to do that the response is `statusCode: 400` with `message: "NotSupported"`.

**Comment by ali-hamud** [comment]
can you please give a code snippet of what you did?

**Comment by soodik323** [comment]
I have same issue, i also got "NotSUpported"
![notsupport](https://cloud.githubusercontent.com/assets/7287519/26541368/0c15517a-445e-11e7-87e0-99ff1cb43c60.PNG)
![notsupport2](https://cloud.githubusercontent.com/assets/7287519/26541350/ffa8d43e-445d-11e7-876d-78edd8582adf.PNG)

**Comment by taarskog** [comment]
This is the essential parts of the code.

**Code to embed:**
```
let config = {
	type: "report",
	accessToken: token,
	embedUrl: this.getEmbedUrl(),
	id: id,
	permissions: models.Permissions.Read,
};

let powerbi = new service.Service(factories.hpmFactory, factories.wpmpFactory, factories.routerFactory);
this._activeReport = powerbi.embed(this._pbiContainer, config);
```

**Code to refresh:**
```
auth.authAboutToExpireCallback = () => {
	auth.getToken().then(token => { this._activeReport.setAccessToken(token) });
}
```

**Comment by taarskog** [comment]
And I am using powerbi.com

**Comment by ali-hamud** [comment]
There was a bug which is fixed. the fix is in the deployment queue. It should be available in 1-2 weeks.

**Comment by ali-hamud** [comment]
Hi @taarskog 
can you please check if you still have the same problem?

**Comment by taarskog** [comment]
Hi @ali-hamud,

I can confirm that it is working. I have tested both reports and tiles. Thank you. 👍
