### ISSUE TITLE
Not able to set default page using 'pageName' or using 'setPage'

### ISSUE THREAD

**Issue by sacmeterprogram** [Microsoft/PowerBI-JavaScript#202]
var embedConfiguration = {
	type: 'report',
	accessToken: 'myaccesstokenhere',
	id: 'myreportidhere',
	embedUrl: 'myembedurlhere',

	settings: {
	    filterPaneEnabled: false,
            navContentPaneEnabled: false
	 },
	pageName: 'pagetwo'
};
var $reportContainer = $('#reportContainer');
var report = powerbi.embed($reportContainer.get(0), embedConfiguration);

This returns the first page of the report aka 'pageone'.

Using the setPage method below:

report.setPage("pagetwo");

This does nothing also. Errors I get include not a valid page name (I doubled and triple checked that it's right). I've also tried to use report.getPages() and reference a page in the array but that doesn't work either.

Is this a bug or am I misinterpreting the syntax?

Thanks,
Noah

**Comment by noanu** [comment]
Hi Noah,

Please take a look here at our live demo https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html# - I think it might help.
Also, please note that getPage returns a "Page" object that has 2 fields: name and displayName. You should set the page to the "name".
You can see the structure of the Page object in our models' gitHub here:
https://github.com/Microsoft/powerbi-models/blob/master/src/models.ts

please let me know if you managed to solve the issue.

**Comment by sacmeterprogram** [comment]
Yes, that fixed it ☺ I was using the display name and not the actual name.

Thanks again,
Noah
