### ISSUE TITLE
Report Rendered Event not firing now 

### ISSUE THREAD

**Issue by rustagirohit** [Microsoft/PowerBI-JavaScript#203]
Hi in my app , report rendered event was working pretty fine , but off sudden today it has stopped firing.
My code implementations associated with this rendered event are not working now. Please let me know incase there is something i can work around on to get this fixed.

**Comment by noanu** [comment]
Hi @rustagirohit 
Thanks for letting us now.
We are investigating this now and will update soon.

**Comment by vangorra** [comment]
This looks like an issue with the PowerBI service. We have several deployment environments all experiencing the same issue. One environment hasn't changed in over a month while another changed yesterday.
This is the second major issue in a week. My company is growing very nervous about the reliability of the Power BI service as a whole and has even mentioned we write our own system. Please get your stuff together and save me a lot of dev time!

**Comment by freshdev1** [comment]
I am facing the same issue, this thing put me in a very embarrassing situation with my client. A week ago I prepared the demo and showed it to my team. The manager and me then prepared to show it to the client, and at once day before yesterday while I was presenting the demo the event didn't fire and the underlying logic didn't work.

Team kindly correct this error, asap, this is a major issue. I fear we might loose getting a project if this is not corrected. Keep up the hard work.

**Comment by noanu** [comment]
Hi guys,

We have already checked in a fix for this issue. It should arrive to production in ~2 weeks.
Next week we will have a discussion and see if it is possible to port it faster to production. 
I apologise for this, and thank you all for you feedback.

**Comment by freshdev1** [comment]
Guys any update on this?

**Comment by noanu** [comment]
Hi,
The fix should arrive to production today or tomorrow.
Please update here when it is resolved for you. thanks.

**Comment by freshdev1** [comment]
Sure I will do that. Thanks for the prompt reply.

**Comment by jfolds** [comment]
`rendered` event has started firing again for me.

**Comment by freshdev1** [comment]
Its working for me too. Keep up the hard work! 👍
