### ISSUE TITLE
Report Map Layer Not Working in Embedded

### ISSUE THREAD

**Issue by haonrolyat** [Microsoft/PowerBI-JavaScript#205]
I am not able to get the map in my report to work in the embedded dashboard. It works fine in PowerBI Desktop. I save and import the file into my Azure workspace and then when I use the JavaScript to embed, everything else works great except the map doesn't load it's feature layer, just the basemap shows at the world level. I have seen in the example, https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html#, that their map is still working. When I use my token and id's in this example, my report loads but not my map point layer - I see the same issue with my own web page. There are no errors being thrown in the console. 

**Could this be a problem with the workspace on Azure or is this a bug on the JavaScript end**? I have reuploaded and resaved the report a few different times and I see the same issue.

Appreciate any insights
Noah

**Comment by sacmeterprogram** [comment]
I made a new workspace on Azure, imported a newly exported file, and I am seeing the same issue where the map container appears with the basemap and legend but there are no points appearing on the map using the embedded api. It works fine on the Power-bi Desktop. Any ideas on this?

**Comment by haonrolyat** [comment]
I made a new workspace on Azure, uploaded a new powerbi file, and I am seeing the same issue where the basemap and legend appear but there are no points on the basemap. Any ideas on this? Since I can't get it to work on the embedded example using the tokens I generate, I am wondering if this is some issue with the Azure Workspace but I can't be sure. Any ideas?

**Comment by ali-hamud** [comment]
Hi @haonrolyat

As I understand, you see the points in Power BI Desktop, but you don't see them in embedded view.
please help us to get a repro for your problem so we can solve it.

can you please tell how many points you expect? is there a lot of points (thousands) or few?
can you describe the schema?
do you see any errors or warnings in console menu?

Thank you.

**Comment by haonrolyat** [comment]
Hi Ali-Hamud,

It turns out that Power BI Desktop broke something in their versioning with embedding. I ended up having to update to a newer version of Power BI Desktop that was just released and this solved my issue. My apologies for not following up.

Thanks,
Noah

**Comment by ali-hamud** [comment]
Thank you :)
