### ISSUE TITLE
Not able to create workspace in Azure

### ISSUE THREAD

**Issue by kksevta** [Microsoft/PowerBI-JavaScript#207]
Hi
I am trying to create Power BI embeded workspace in Azure as mentioned [here](https://docs.microsoft.com/en-us/azure/power-bi-embedded/power-bi-embedded-get-started).
But when I click at Power BI embeded , it is not redirecting me to Workspace creation page. Rather I am able to see only  

![capture](https://user-images.githubusercontent.com/11193293/27001020-41060b80-4ddd-11e7-895d-c7771ed94148.PNG)

What am I missing?
Kindly help

Thanks & regards
Kuldeep

**Comment by ali-hamud** [comment]
Hi we moved to a new way of embedding reports,dashboards and tiles.
You don't need Azure workspaces anymore.

Please follow this documentation to prepare your env:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-using-embed-token/

And these are code samples that you may use:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html
https://github.com/microsoft/powerbi-developer-samples (use AppOwnsData)

please let me know if you face any issues.

**Comment by kksevta** [comment]
@ali-hamud 
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-using-embed-token/
is not working for me.

Btw I think this method is one of three steps to embed power BI inside webapp. But AFAIK in this case every user has to have Power BI Pro or altleast power BI login.

But I need to embed using power BI embedded Azure service where user does not need any Power BI licence.

**Comment by ali-hamud** [comment]
We moved here:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding-content/

Don't use azure anymore. it will be deprecated.
Use https://github.com/microsoft/powerbi-developer-samples (use AppOwnsData)
As Application, you will need one Power BI user (see documentation link above).
Users of your application will not need power bi users.

please read the documentation, and if you have more questions let me know.

**Comment by kksevta** [comment]
@ali-hamud  Thanks 
I will try this way and let you know if I have faced any problem.

**Comment by kksevta** [comment]
Well I have AppOwnsData and I don't how to get the group's ID required in web.config

**Comment by ali-hamud** [comment]
Just create an App Workspace in Powerbi.com
then you can take the the Id of this workspace from the url (e.g. Guid object).

For the following url, the group id is: a0cc9bb0-0a17-468d-a6c0-d5d0dcea1d31
https://app.powerbi.com/groups/a0cc9bb0-0a17-468d-a6c0-d5d0dcea1d31/contentlist

**Comment by kksevta** [comment]
Sorry for the updating same comment as I got the App ID in between.. 
I am getting the updated Unauthorized error.

**Comment by ali-hamud** [comment]
are you sure the GroupId is ok?
what do you see in fiddler? which request fails?
do you have requestID?

**Comment by kksevta** [comment]
Yeah Group ID is okei 
as the links works for me
https://app.powerbi.com/groups/**{groupid in webconfig}**/contentlist/

and I copy it when I publish the workspace.
![capture](https://user-images.githubusercontent.com/11193293/27084734-9046b5fc-506a-11e7-9794-43d4c8b2e24e.PNG)


and following is stack trace
![capture22](https://user-images.githubusercontent.com/11193293/27085048-c2bd1f34-506b-11e7-88fd-ba1901244b3f.PNG)

**Comment by ali-hamud** [comment]
Do you have request Id in fiddler?
or you can hit F12 to open Developer tools, and copy a request id from headers of the failed request.

**Comment by kksevta** [comment]
request URL is http://localhost:42734/Home/EmbedDashboard
But I am not able to see any request id header
![capture](https://user-images.githubusercontent.com/11193293/27085534-2c3c8f34-506d-11e7-9202-119b6bffab0e.PNG)

**Comment by kksevta** [comment]
Redirect URL is http://localhost:42734/ in AAD registered apps
while the homepage URL is blank. 
Could this be the reason?

**Comment by kksevta** [comment]
As I was using app id , I replaced it with proper id. I apologize 
Everything start working but again with one more  error.
Getting 401 for this request 
Request URL:https://wabi-us-north-central-redirect.analysis.windows.net/metadata/cluster

reques Id: b0060f07-5fdf-6e5a-38c2-89d7e93140e5

**Comment by ali-hamud** [comment]
This is a known problem that we are fixing. The fix will be available soon.
For now, I can offer a mitigation, but first can you search a request which looks like the following and copy the response you get?
v1.0/myorg/groups/<groupId>/dashboards

**Comment by ali-hamud** [comment]
can you please send email to: pbieci@microsoft.com
and I will reply with a mitigation.

**Comment by kksevta** [comment]
Well I can't  find any request which is matching to  **v1.0/myorg/groups//dashboards**

**Comment by kksevta** [comment]
Thanks  @ali-hamud
issue has been resolved for me.

**Comment by shaximinion** [comment]
Hi,

I'm using the `PowerBI-Developer-Samples/App Ownes Data` solution and I'm having the same issue and cannot get past this.  I have tried to use the Group GUID (obtained by using [http://docs.powerbi.apiary.io/#reference/groups/list-all-groups?console=1](url) and also by clicking in the App workspace and getting it from the URL: [https://app.powerbi.com/groups/me/apps/1ddXXXXXXXXXXXXXXXXXXXXXXXXXXXXXf05](url) - they both return different GUIDs but both do not work.

I get the same 

> Operation returned an invalid status code 'Unauthorized'

error.

Regards,

Shaheen
