### ISSUE TITLE
'dataSelected' event is not fired if SelectionManager doesn't return data

### ISSUE THREAD

**Issue by olehkazban** [Microsoft/PowerBI-JavaScript#209]
Hello.
May be this is not a real issue, but feature. I have web app (Angular 4) with PowerBI embedded report (this report uses custom visual). I receive this event in my app in case if SelectionManager.Select() returns array of selected items. But in case of second click on the same item SelectionManager.Select() returns an empty array and this event is absent.
In any case I'd like to receive this event even with empty data in my app.
My workaround is:
```
this.report.on('dataSelected', (event) => {
    console.log('dataSelected: ', event);
});
```

Best regards.

**Comment by noanu** [comment]
Hi @olehkazban 
We've already checked in a code that returns an empty data in case of deselecting a dataPoint :)
This code should arrive to production in a week or two. 

thanks!

**Comment by noanu** [comment]
I am closing the issue, feel free to reopen it if needed.

**Comment by olehkazban** [comment]
Thanks!
