### ISSUE TITLE
I am wondering if this library is using `Power BI Rest APIs` internally ?

### ISSUE THREAD

**Issue by vsymguysung** [Microsoft/PowerBI-JavaScript#210]
I am referring the  [Power BI Rest APIs](http://docs.powerbi.apiary.io/#introduction/what-can-i-do-with-the-power-bi-api?).

If not, what is the difference between `PowerBI-JavaScript` lib and `PowerBI Rest APIs` ?

Thanks.

**Comment by ali-hamud** [comment]
We have two main SDKs:
1) PowerBI-JavaScript: helps for embedding reports, dashboards and tiles and interacting with embedded entity.
Github: https://github.com/Microsoft/PowerBI-JavaScript (e.g. current)
Nuget: http://www.nuget.org/packages/Microsoft.PowerBI.JavaScript/

2) PowerBI-API: helps for calling REST APIs. It can be used for example for Getting reports metadata, or creating a new dataset, or generating embed token to embed a report and a lot more.
Github: https://github.com/Microsoft/PowerBI-CSharp
Nuget: http://www.nuget.org/packages/Microsoft.PowerBI.Api/

Here is a full sample that uses both (e.g. API for management, Javascript for embedding):
https://github.com/Microsoft/PowerBI-Developer-Samples
