### ISSUE TITLE
403 Forbidden N

### ISSUE THREAD

**Issue by priyazeem** [Microsoft/PowerBI-JavaScript#212]
![issue](https://user-images.githubusercontent.com/15958490/27306548-02dd0be0-5514-11e7-842c-403e09868889.PNG)

I am trying to embed a report using Java script but getting the attached error. Following are the steps I did:
- created app workspace in Power BI with my ID (I have pro license)
- published report and updated Azure SQL DB credentials in data set
- noted report ID, group ID from URL in power BI
- registered an app and gave permissions as mentioned in the guide - https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding-content/
-

**Comment by ali-hamud** [comment]
This problem should be fixed already.
Please let me know if you still have the same problem.

**Comment by ali-hamud** [comment]
please re-open if it's not fixed for you.

**Comment by kristianoftedal** [comment]
Im having the same issues 

![image](https://user-images.githubusercontent.com/10758344/29812652-9c20bdd6-8ca7-11e7-88e6-91ca543e73bf.png)
