### ISSUE TITLE
How to generate embed token?

### ISSUE THREAD

**Issue by priyazeem** [Microsoft/PowerBI-JavaScript#213]
Hi Guys,

I have been struggling from long to embed reports into my Angular JS2 app.
There are lot of documentation and I am confused with the following:
- how do I generate embed token? is it same as azure ad token?
- what should be the embed url? https://app.powerbi.com/appTokenReportEmbed... or https://embedded.powerbi.com/reportEmbed?

Please help me. Now it shows NotAuthorized when I try to embed with right azure ad token

**Comment by somriar** [comment]
Hey,
- Here is a documentation on embedding reports/dashboards/tiles:
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/

- Here is the documentation on creating embed token:
https://msdn.microsoft.com/en-us/library/mt784614.aspx
as explained on the documentation it is not the same as azure ad token

- You should use https://embedded.powerbi.com/reportEmbed

**Comment by wdnlwzd** [comment]
Hi somriar,

I want to konw,
what is the relationship between client_id and group_id ?

thanks.

**Comment by ali-hamud** [comment]
There is no relationship.

client id: you get it after you register an app in AAD.
group id: you can get it by calling v1.0/myorg/groups API, or using Microsoft.PowerBI.API nuget package. or you can take it from the report URL in powerbi.com (group id is the workspace ID in Power BI portal).

just read the documentation that @somriar gave you and it will work for you.

**Comment by wdnlwzd** [comment]
Ok,

Thank you for your answer.
