### ISSUE TITLE
Print removed?

### ISSUE THREAD

**Issue by brannmar** [Microsoft/PowerBI-JavaScript#215]
Hi!
Is it no longer possible to print an embedded report using the javascript api? The print instructions was removed from the markdown latest change. 

Is it going to be replaced with an other equal functionality? Or are we left with the standard way of printing from an embedded report using `window.print();`?

What i can see from these two links: 
[Allow printing from power bi embedded](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/15295617-allow-printing-from-power-bi-embedded)
[Print and Export Embedded Reports through REST APIs](https://ideas.powerbi.com/forums/265200-power-bi-ideas/suggestions/12288612-print-and-export-embedded-reports-through-rest-api)

it is planned but there is no status update since December 2016. 

Please give us some updates regarding this.

**Comment by ali-hamud** [comment]
print was not removed.
it was removed by mistake from Wiki.
here it is:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embedding---Basic-interactions#print-a-report

By the way: report.print() in its current implementation uses window.print().
We know it's not the best, we have a task in our backlog to improve this.
Thanks.

**Comment by brannmar** [comment]
Thank you Ali!

Closing the issue.
