### ISSUE TITLE
powerbi.embed(embedContainer, config) doesn't work with iFrame.

### ISSUE THREAD

**Issue by KNaved** [Microsoft/PowerBI-JavaScript#216]
powerbi.embed(embedContainer, config) doesn't work with iFrame.
It works with div but doesn't work with iFrame. Can someone please let me know if i am missing anything.

Here is my code 

            var txtAccessToken = "@Model.AccessToken";
            var txtEmbedUrl = "@Model.EmbedUrl";
            var txtEmbedReportId = "42f4b59d-4545-4469-8d53-b65adb220150";
            var models = window['powerbi-client'].models;
            var config = {
                type: 'report',
                tokenType: models.TokenType.Embed,
                accessToken: txtAccessToken,
                embedUrl: txtEmbedUrl,
                id: txtEmbedReportId,
                permissions: models.Permissions.All /*gives maximum permissions*/,
                viewMode: models.ViewMode.Edit,
                settings: {
                    filterPaneEnabled: true,
                    navContentPaneEnabled: true
                }
            };

            var embedContainer = $('#dashboardIframe')[0];
            var report = powerbi.embed(embedContainer, config);

**Comment by thomasvhaastrecht** [comment]
The container should not be an iframe, it will contain one, however. The code will inject an iframe into your div, so from what you are telling us, it sounds like everything is working as intended. If you want to add specific styles to the iframe you will want to add one along the lines of:
`div iframe 
{
  //insert styles here
}`
