### ISSUE TITLE
How to add filters for columns with the data type BigInt

### ISSUE THREAD

**Issue by jfloodnet** [Microsoft/PowerBI-JavaScript#217]
This is a bizarre issue that I encountered today.

When adding a filter such as this:

               {
                    target: {
                        table: 'MyTable',
                        column: "Id"
                    },
                    operator: "In",
                    values: [123]
                }

I was getting the error 'The filter can't be used since the corresponding field is invalid'

For the life of me I couldn't figure this out. I could filter on all the other columns. I could filter columns on other tables with the name 'Id'.

By this point I was willing to try anything to get it working. The only difference I could see between this column and other columns was that it is a BigInt!

So I thought, in my js, how could I make my integer a big one?? 

You wouldn't believe it, but the solution was "parseFloat"??

And here is the filter that worked:

               {
                    target: {
                        table: 'MyTable',
                        column: "Id"
                    },
                    operator: "In",
                    values: [parseFloat(123)]
                }

JavaScript, the good parts :)

**Comment by ali-hamud** [comment]
I have no idea why this worked.
parseFloat(123) returns number.
123 is also a number.
I will check that.

**Comment by jfloodnet** [comment]
yep neither did I.... but I've had a bit more time to think about this...

Obviously the code above was somewhat contrived. The actual code was closer to this:

          var whereId = id => {
                return {
                    target: {
                        table: 'MyTable',
                        column: "Id"
                    },
                    operator: "In",
                    values: [id]
                }
            };

Turns out that 'id' was actually a string coming from code like this:

    var id = '@Model.Id';

So the real fix was to do this:

    var id = @Model.Id;

Still somewhat elusive behaviour.

**Comment by ali-hamud** [comment]
Now it makes sense.
This behavior is good actually. Thanks for commenting again.
Anyway, You should not be able to filter int column with string. works this way in almost every environment I know (e.g. SQL, DAX, ...)
I am closing the comment. please let me know if you need any help.
Thanks.

**Comment by jfloodnet** [comment]
Yes, I think that's fair enough. Hopefully this issue will help someone if they encounter the same problem.

Cheers,
