### ISSUE TITLE
Sample report not embedding (Google Chrome) 

### ISSUE THREAD

**Issue by brannmar** [Microsoft/PowerBI-JavaScript#219]
When using Chrome to view the sample report it is not possible to embed the report. (https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html)

Getting 500 internal server error when trying to embed it.

![image](https://user-images.githubusercontent.com/7968452/27679597-7f9818a8-5cb9-11e7-9c27-05003101c217.png)

![image](https://user-images.githubusercontent.com/7968452/27679675-afa52b94-5cb9-11e7-9afd-7618dfa425f0.png)

**Comment by noanu** [comment]
Hi @brannmar 
Could you please give more details? Exact steps so that we can reproduce the experience?
I just tried now to embed the sample report in the live demo (the same link you provided) and all looks fine, so I guess you are doing something different.
thanks.

**Comment by brannmar** [comment]
Using Chrome Version 59.0.3071.115 

1. Entering page
![image](https://user-images.githubusercontent.com/7968452/27685679-8a2c6420-5ccf-11e7-8dcf-5648595848a2.png)

2. Clicking embed sample report ()
![image](https://user-images.githubusercontent.com/7968452/27685714-bc3d19e6-5ccf-11e7-9b21-07e3079ad8eb.png)
Console output:
![image](https://user-images.githubusercontent.com/7968452/27685731-d64b7968-5ccf-11e7-9706-d0290b3a5380.png)

Clicking run 
![image](https://user-images.githubusercontent.com/7968452/27685826-27e5ceb8-5cd0-11e7-80b4-845e1b9fde8b.png)

Getting 500 error
![image](https://user-images.githubusercontent.com/7968452/27685843-3e2633de-5cd0-11e7-90e7-274e83b06468.png)

Attaching request dump
[microsoft.github.io.har.zip](https://github.com/Microsoft/PowerBI-JavaScript/files/1111868/microsoft.github.io.har.zip)

**Comment by noanu** [comment]
Hi @brannmar 
Thanks for the details!
We will continue the investigation on Sunday. Please update here if you have any new information.

**Comment by ali-hamud** [comment]
Hi @brannmar,
do you still face the same issue?

**Comment by ali-hamud** [comment]
closing issue as no response.
