### ISSUE TITLE
Embedding with Power BI Premium

### ISSUE THREAD

**Issue by thomasvhaastrecht** [Microsoft/PowerBI-JavaScript#220]
Not sure if this is the best place to ask this question, but there is not much documentation on the subject elsewhere and this is the JavaScript GitHub, so I figured i would give it a shot (if there is a better place to ask the question, then kindly point me in the right direction).

In regards to Power BI Premium, will the JavaScript API still be an option for embedding reports into external applications once the switch from Power BI Embedded to Power BI Premium takes place?

I have looked online and all I have heard in regard to this is that the REST APIs will need to be used, as well as a switch from Azure Active Directory workspaces to Power BI app workspaces. Is there anything huge that I am missing? Any info would be greatly appreciated, and I imagine this will be important information for some other people too.

**Comment by ali-hamud** [comment]
Yes, PowerBI-Javascript is still in use.
**Documentation**: https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding/
**E2E sample solution**: https://github.com/Microsoft/PowerBI-Developer-Samples
