### ISSUE TITLE
DateTime advanced filter condition applies incorrectly

### ISSUE THREAD

**Issue by monokarp** [Microsoft/PowerBI-JavaScript#222]
I noticed that when applying an advanced filter to a DateTime column, both 'GreaterThan' and 'GreaterThanOrEqual' expressions seem to evaluate to 'GreaterThan'. 'LessThan' expressions apply correctly though. This only manifests when applying the filter to my DQ-based report, the others that are using data import work fine.
I was also able to reproduce this behavior in your [app sample](https://microsoft.github.io/PowerBI-JavaScript/demo/filters.html).

Thank you in advance.

**Comment by noanu** [comment]
Hi @monokarp 
Could you please provide us detailed repro steps? (table name, column name, page of report etc.)

**Comment by monokarp** [comment]
Sure:
District Monthly Sales report page
Table: Time, Column: Date, Operator type: Advanced, Logical Operator: And
First Value: 2014-02-01T00:00:00.000Z, Condition: GreaterThanOrEqual
Second Value: 2014-04-01T00:00:00.000Z, Condition: LessThanOrEqual
When applied, I'd expect to see Feb Mar Apr on the chart on the bottom left, but it only shows Mar and Apr.

**Comment by noanu** [comment]
Thanks @monokarp,
I managed to see the repro.
I will look into it and update when there are any news.

**Comment by noanu** [comment]
Hi @monokarp 
I did some investigation and the problem is actually with the way you define the time zone of the value you passes. When you don't define it as UTC (remove the Z from the end of the value), it works as expected. Please play with the time zone deinition to understand which time zone you should use on your data.
