### ISSUE TITLE
Does PowerBI embed support multiple language?

### ISSUE THREAD

**Issue by TisnKu** [Microsoft/PowerBI-JavaScript#224]

**Comment by ArinaHantsis** [comment]
Hey TinsKu,

**Comment by ArinaHantsis** [comment]
Power BI Embedded currently supports browser header locale if such locale supported by PowerBI.com. Towards mid August we'll provide the user an option to specify the language to embed API and control UI language and locale formatting (dates, currency etc.)

**Comment by joukevandermaas** [comment]
This would be really great to have. Any status update?

**Comment by noanu** [comment]
Hi @joukevandermaas 

Yes! the support is already available in production - you can look here:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details
