### ISSUE TITLE
is getReports() supported?

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#226]
Hi,

Does this support getting the list of reports from a specific workspace?  

https://msdn.microsoft.com/library/mt634543.aspx

I'm not seeing it in the code base? Is this library strictly for displaying reports given that the report ID is known?  Or does it allow you to retrieve a list of reports and then from there display the reports by embedding it?

Thanks,
Derek

**Comment by ali-hamud** [comment]
This library allows you embed a report/dashboard/tile and interact with them.
It needs as input: embed URL and Embed Token.

If you want a library which gives you a list of reports, or creates an embed token (i.e. Managament library) please use this:
https://github.com/Microsoft/PowerBI-CSharp

It's available in Nuget: Microsoft.PowerBI.Api
