### ISSUE TITLE
IE11 can't call reload

### ISSUE THREAD

**Issue by ruisilva450** [Microsoft/PowerBI-JavaScript#227]
Hi,

I'm trying to fix an memory leak issue with the iframe on IE11 when I was using the 1.1 version of this library. 
Then I tried to upgrade for 2.3.2 and notice that there is a reload function but when I try to use it I see that internally it uses promises, which IE11 doesn't support natively.

Is there a way of fix this?

**Comment by noanu** [comment]
Hi @ruisilva450 
In the new version we defined es6-promise in package.json which is a polyfill for promise.
Can you make sure that this dependency is installed correctly in your solution?

**Comment by ali-hamud** [comment]
reference issue:
https://github.com/Microsoft/PowerBI-JavaScript/issues/92
