### ISSUE TITLE
can this library be used in pre-rendering.  Dependency issues with window object

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#230]
I"m currently using a .net core react-redux SPA application that utilizes this library.  .net core has a feature that allows you to do some pre-rendering.  However, when this is enabled it throws an exception that it doesn't know what the 'window' object is.   

I haven't had a chance to really look into the code base, but is there a big dependency on the window object and is it possible that this library could be implemented without the usage of the 'window' object?

Thanks,
Derek

**Comment by ali-hamud** [comment]
window object is used for two things:
1) save powerbi instance - we can check for window!=null before saving which will save your problem.
2) postMessage between iframe and your app. this cannot be replaced. messages are used to render the report first time, and then to listen to user interactions, or change the report (e.g. setFilters)

please let me know if you find a solution.

**Comment by darewreck54** [comment]
@zakharBorodin this would be more of a feature request then closing the issue since there was no real solution?
