### ISSUE TITLE
Adding ability to get the report object without rendering at first

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#232]
Hi,

I was wondering if it's possible to get the report object and then from there determine when to embed the iframe.  It seems that you need to embed/render the iframe before you can get the report object.  This limits the flexibility of the library.  

Thanks,
Derek

**Comment by noanu** [comment]
Hi @darewreck54 
This issue seems like a duplication of this one: 
https://github.com/Microsoft/PowerBI-JavaScript/issues/231
I am cloising this issue, please feel fre to reopen it and comment if I am wrong.
