### ISSUE TITLE
getFilters() does not return the non selected filters

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#233]
Hi,

This is in reference to the json returned by the getFilters() for pages

1. It seems that when you get the filters for the pages, it only returns the selected filters.  There is no way to know what filters were available.
2. The operator is always set to "all."  In the live demo example, the have the options to do basic filter vs. advance and this isn't show in the json.
3. For advance filter, the json shows no representation of that at all either.

Thanks,
Derek

**Comment by noanu** [comment]
1. We are aware of this need, and have it in our backlog to add support for getting this information.
2. This information is in the "schema" field. Please take a look at this gitHub and consider using it in order to interact with the javascript-sdk better:
https://github.com/Microsoft/powerbi-models
This code gives you an API for handling the types that the javascript-sdk uses.
3. We will take a look at this - it might be a bug/enhancement that we need to address. We will update.

**Comment by darewreck54** [comment]
@noanu 

2) Thanks for giving me a reference to the schema types.  From looking at it, how would you tell if the user selected a basic vs. advancedFilter type.  The type is defined as "object" for both.    Why not define the type as "advance" vs. "basic" .  This might making consuming the data easier.  I can create put this issue on that repo as well if it makes more sense.

Thanks!

**Comment by noanu** [comment]
Hi,
you can use getFilterType function - it is in powerbi-models.

**Comment by ali-hamud** [comment]
@darewreck54 
There are no bugs with getFilters.
I think in the live demo, you called getFilters which gives report level filters. you also has a code which gives you page level filters.

please open this issue if you still need anything.

**Comment by darewreck54** [comment]
@ali-hamud The issue is that page getFilter does not return the unselected filters.  It only returns the selected filters.  Please take a look at the json return and examine the values in comparison to the page filters.

**Comment by noanu** [comment]
Hi @darewreck54 
Can you specify what do you mean by "unselected filter"?
getFilters returns basic filters that are set to "all", which is a kind of unselected filter.
Regarding all the other filters that don't appear in the filter pane - you are right, we don't return them. They are determined only by the model's schema, so you, as the developer, can build them yourself if you know your model structure.
It is in our backlog to have an API to get information about the model's schema (and this will enable to know the available filters) but I don't have an ETA for it.

**Comment by darewreck54** [comment]
@noanu THanks for your response.  I was actually referring to the filter schema of the models.  I wanted to reconstruct the filters without having to be part of the embedded iframe.  To do that I need all the values of the fitlers (the model/schema), possible operator selection as well.  

In the original post:

```
1. It seems that when you get the filters for the pages, it only returns the selected filters. There is no way to know what filters were available.
2. The operator is always set to "all." In the live demo example, the have the options to do basic filter vs. advance and this isn't show in the json.
3. For advance filter, the json shows no representation of that at all either.
```

Questions:

- Is there a work work item to track number 1 since an update to the API to get the model schema would resolve that?
- is there a work item to track the support of having the filter set to something other then "all"
- is there a work item to track the support of advance filters since it only support basic

Thanks
Derek

**Comment by noanu** [comment]
Hi @darewreck54 ,

I will address your questions:
1. This is in our backlog (not sure what do you mean by "work item"). When we add this API it will enable to build the possible filters. 
2. I don't understand this question. What do you mean by a fitler set to something "other then all"? We return filters with all other operators as well - like In/Not In for basic filter
3. Again, this question is not clear to me. Did you mean that we only support basic filter when the filter set to "all"? that is correct - we don't return advanced filters set to all and this is a bug. We are aiming to fix it soon, when we have an ETA we will update.

**Comment by darewreck54** [comment]
sorry "work item" just refers to a way to track it similar to this GitHub filed issue.  Since this issue was closed, I wasn't sure how I would track it or if you guys would update a closed issue once the fix is done.

I think you were able to address all the questions with the response of how there are backlog items for both the api to address possible filter and the support for advance filter.  

Thanks,
Derek
