### ISSUE TITLE
not able to set filter

### ISSUE THREAD

**Issue by secabhi** [Microsoft/PowerBI-JavaScript#237]
Hi I am trying to set filter like this
`const filter = {
  $schema: "http://powerbi.com/product/schema#basic",
  target: {
    table: "micro trans",
    column: "pyramid"
  },
  operator: "In",
  values: ["PH"]
};
var config= {
    type: 'report',
    tokenType: models.TokenType.Embed,
    accessToken: txtAccessToken,
    embedUrl: txtEmbedUrl,
    id: txtEmbedReportId,
    permissions: permissions,
    filter:filter,
    settings: {
        filterPaneEnabled: true,
        navContentPaneEnabled: true
    }
};

// Get a reference to the embedded report HTML element
var embedContainer = $('#embedContainer')[0];
 
// Embed the report and display it within the div container.
var report = powerbi.embed(embedContainer, config);

report.setFilters([filter])
    .then(function (result) {
        Log.log(result);
    })
    .catch(function (errors) {
        Log.log(errors);
    });
`
But Its not updating in UI

**Comment by ali-hamud** [comment]
you need to wait to report loaded event and set the filter there.
example:
report.on("loaded", function () { report.setFilter.. });

**Comment by secabhi** [comment]
thanks for ur help . I just passes report reference to report.on("loaded", function () {},report) . n it worked
