### ISSUE TITLE
carouselNavButton nextPage and previousPage not working with small browser windows.

### ISSUE THREAD

**Issue by matheuscarboni** [Microsoft/PowerBI-JavaScript#239]
Naming one or more tabs in a report with a name that exceeds the width of the browser window will prevent the scroll buttons from working. Here's an example of what the tabs look like when I increase the browser window:
![image](https://user-images.githubusercontent.com/20691499/29078778-fc78745e-7c20-11e7-8d28-6a4c2a5c9b08.png)

However, if I decrease the width of the browser window, I see the following:
![image](https://user-images.githubusercontent.com/20691499/29078843-1c834080-7c21-11e7-8c5b-83b129fdc073.png)

The issue with the second picture is that although I can select the ">" button, the carousel wont scroll further to display the other two tabs.

Edit: This only happens while using powerbi.js and embedding the report onto a page.

**Comment by ali-hamud** [comment]
Hi @matheuscarboni 
Thank you for opening this issue.
can you please tell what browser and OS you have?

**Comment by matheuscarboni** [comment]
I've tested on Chrome, IE, and Firefox, both on Windows 10 and Windows 7.

**Comment by ali-hamud** [comment]
Thank you. 
does it happen in powerbi.com as well? or just in embedded report?

**Comment by matheuscarboni** [comment]
Only in an embedded report, I should add I've tested this without any added CSS or JavaScript and the problem remains.

**Comment by ali-hamud** [comment]
@matheuscarboni 
I have a feeling that your iframe width is below the minimum (which is 300).
is that true?

**Comment by ali-hamud** [comment]
closing as no response.
