### ISSUE TITLE
setFilters for report not working with TypeScript

### ISSUE THREAD

**Issue by PhatHoang21** [Microsoft/PowerBI-JavaScript#243]
I loaded my embedded report, but I couldn't apply a filter. Any one face the same problem?
`let config = {
  type: 'report',
  tokenType: 1,
  accessToken: this.token,
  embedUrl: this.embedUrl,
  permissions: 7,
  settings: {
    filterPaneEnabled: true,
    navContentPaneEnabled: true
  }
};

let reportContainer = document.getElementById('powerBIContainer');
let powerBiService: pbi.service.Service = new pbi.service.Service(
pbi.factories.hpmFactory, pbi.factories.wpmpFactory, pbi.factories.routerFactory);

let report = <pbi.Report>powerBiService.embed(reportContainer, config);
const basicFilter: pbimodels.IBasicFilter = {
  $schema: 'http://powerbi.com/product/schema#basic',
  target: {
    table: 'TimeAttendance',
    column: 'FloorId'
  },
  operator: 'In',
  values: [1]
};

report.setFilters([basicFilter]).then(function (result) {
  console.log('Success: ' + result);
}).catch(function (errors) {
  console.log('Error: ' + errors);
});`

**Comment by PhatHoang21** [comment]
It did apply the "where" condition

![powerbifilter](https://user-images.githubusercontent.com/31121315/29771615-fe380c24-8c1e-11e7-802a-3de89d7a8681.PNG)

**Comment by noanu** [comment]
Hi @PhatHoang21 
Can you try to give more details?
Is there any error you see? in the console or catched in your code?

**Comment by ali-hamud** [comment]
closing as no response from customer.
