### ISSUE TITLE
Bug with getFilters() and relative dates filter

### ISSUE THREAD

**Issue by denismc** [Microsoft/PowerBI-JavaScript#244]
Im trying to get filter informations with getFilters() and its working fine with basic and advanced filter.
But when I try to get these same infos filtering by relative dates its returning this error
![capturar](https://user-images.githubusercontent.com/1324565/29819039-416e9f6e-8c95-11e7-9e11-c1f081320605.PNG)

I dont know if it happens with Top N (Bottom) too.

**Comment by noanu** [comment]
Hi @denismc 
I am happy to say that we added support for relativeDate filter a few days ago. It should arrive to production in ~3 weeks.
Regarding topN - this is a visual level filter so getFilters will not return it. However, it should be returned on dataSelected event in the filters property. The code that was checked in a few days ago includes the support for topN filters as well, so it will be returned in dataSelected event in ~3 weeks as well.
By the way, we are working on adding support for visual level fitlers in get/set filters as well.
