### ISSUE TITLE
Support for embedded in different languages settings ?

### ISSUE THREAD

**Issue by dawcza3** [Microsoft/PowerBI-JavaScript#247]
Is there any way to make some configuration files/dynamic replacement for all text which is included in my embedded report with **direct query mode** ? ? I'm just started with code from here : https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details , but it doesn't work and always load report (filters and some grouped names labels) in my current web browser language.

**Comment by ali-hamud** [comment]
Hi,

There was a bug in ducmentation.
please refer to the link you provided again.

correct settings for locale should be:

settings: {
		localeSettings: {
			language: en,
			formatLocale: es
		}
	}

e.g. language and formatLocale should be under localeSetings
