### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Ultralum** [Microsoft/PowerBI-JavaScript#249]
Hi,

I am having similar [issues ](https://github.com/Microsoft/PowerBI-JavaScript/issues/212)as another user.
I am trying to embed a report using Java script but getting the attached error. Following are the steps I did:

- created app workspace in Power BI with my ID (I have pro license)
- published report and updated Azure SQL DB credentials in data set
- noted report ID, group ID from URL in power BI
- registered an app and gave permissions as mentioned in the guide - https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-embedding-content/

![1](https://user-images.githubusercontent.com/31881872/30315012-da32ed3c-97a2-11e7-9605-ff08d55d8896.png)

![2](https://user-images.githubusercontent.com/31881872/30315165-5712c8d6-97a3-11e7-87cf-01e43f29b926.png)

**Comment by ali-hamud** [comment]
can you please check if you pressed the "Grant permission" in azure portal? can you check if the application requested the right permissions?
In addition, please send us a request Id so we can look into our logs and see what you did wrong.

**Comment by Ultralum** [comment]
I have triple-checked Grant Permissions in Azure Portal, so that should not be the issue here.
Here is the request Id:
![3](https://user-images.githubusercontent.com/31881872/30316995-28404ece-97a9-11e7-9495-76530c458b82.png)

**Comment by darewreck54** [comment]
I think with the access token which is a json web token, you can decode it and see what the permission is. 
https://jwt.io/ .  Might tell you what your permissions .

**Comment by ali-hamud** [comment]
Hi @Ultralum 
can you share your load configuration you pass to powerbi.embed method?

**Comment by Ultralum** [comment]
![5](https://user-images.githubusercontent.com/31881872/30469136-5a1cb570-99ef-11e7-872d-4a44b5a7dda2.png)

**Comment by jmikkonen** [comment]
Experiencing the same issue. Noting that using https://msdn.microsoft.com/en-us/library/mt784614.aspx#Anchor_5 to create the access token does not produce a JWT token. If it helps: `RequestId: 245291ea-4695-0769-55fd-c5b394bcb61a`

**Comment by ali-hamud** [comment]
TokenType is missing in your config. it should be:
    tokenType: models.TokenType.Embed,

you can see the sample code in this live demo:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html

**Comment by ali-hamud** [comment]
if you don't have the models object in the previous comment, initialize it this way:
var models = window['powerbi-client'].models;

and if you need a full visual studio samle just download this and change web.config to match your power bi account: 
https://github.com/Microsoft/PowerBI-Developer-Samples/tree/master/App%20Owns%20Data/PowerBIEmbedded_AppOwnsData

**Comment by jmikkonen** [comment]
@ali-hamud Thank you! This seems to solve the issue for me. In the process of testing migration from the old service and I didn't notice the tokenType was missing.

**Comment by ali-hamud** [comment]
I am closing this issue, please re-open if you still have it.

**Comment by Ultralum** [comment]
This solved the issue for me as well. Thank you!
