### ISSUE TITLE
Do not install typings on global side

### ISSUE THREAD

**Issue by lijunle** [Microsoft/PowerBI-JavaScript#25]
Hi,

This project is failing my build because it tried to [install typings globally](https://github.com/Microsoft/PowerBI-JavaScript/blob/master/package.json#L12). As a normal dependency, it should **not** touch my global packages. Please declare typings as your [dependencies](https://github.com/Microsoft/PowerBI-JavaScript/blob/master/package.json#L60) instead.

**Comment by wbreza** [comment]
We will investigate this.  Thanks for reporting.

**Comment by lijunle** [comment]
@wbreza thank you for handling this. I saw the new version is published and resolve this.

**Comment by wbreza** [comment]
Fixed with #26
