### ISSUE TITLE
Importing dataset into existing report?

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#251]
Hi,

When you create a report, you usually select a data source, extract data from there and then pick visualization.

Question:

1. I was wondering if it's possible to import a new datasource into an existing report via the embedded library or if power bi even supports this? I notice that when you go in edit mode, you see data from existing data sources, but not really the ability to upload more data.  Is that possible in edit mode?
2. Is it possible to restrict what a user can do in edit mode?  For example, I wanted to restrict a user from altering specific reports or pages?  

Thanks,
Derek

**Comment by ali-hamud** [comment]
Hi @darewreck54 

1) Yes we have Rebind API, which implemented in the nuget Microsoft.PowerBI.Api if you write C#.
Rebind Report: https://msdn.microsoft.com/en-us/library/mt784672.aspx
Api Nuget: https://www.nuget.org/packages/Microsoft.PowerBI.Api/

2) EmbedToken is per report, when giving EmbedToken to your users, you decide if the token is for view only or for view and edit. once the EmbedToken if for Edit, users can do whatever they want in the report.
I believe that if you want to give edit for your users, you may want to clone the report first and give them edit on the new report, so, you will have your backup.
more about EmbedToken and clone in these links:
Clone report: https://msdn.microsoft.com/en-us/library/mt784674.aspx
Embed Token: https://msdn.microsoft.com/en-us/library/mt784614.aspx

**Comment by darewreck54** [comment]
@ali-hamud 

Thanks for the response.

1) Doesn't seem like the api nuget is support for .net core 2.0 

`warning NU1701: Package 'Microsoft.PowerBI.Api 2.0.3' was restored using '.NETPortable,Version=v0.0,Profile=Profile259, .NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.`

Because of that i need to go the API route.  However the documentation is really limited.  I understand the parameters for the url, but not really the body.

`{
  "datasetId": "string"
}`

What does the datasetID reference?  Does that refer to an existing uploaded dataset into power bi?  Is there a way to upload a whole new data set into the report vs just referencing an existing dataset that may not be associated with the report.?  

Thanks,
Derek

**Comment by darewreck54** [comment]
Actually just found links to https://msdn.microsoft.com/en-us/library/mt203567.aspx on accessing dataset and creating them.  

So you would have to create or get the data set and then associate with it.
