### ISSUE TITLE
Return the report id on saveas.

### ISSUE THREAD

**Issue by iwollmann** [Microsoft/PowerBI-JavaScript#254]
How can I get the id of the new report after doing a saveas operation?

**Comment by ali-hamud** [comment]
you should listen to saved event to get the new id after save complete. please relate to this article:

https://docs.microsoft.com/en-us/azure/power-bi-embedded/power-bi-embedded-create-report-from-dataset#automate-save-and-load-of-a-new-report-using-the-saved-event
