### ISSUE TITLE
Could not serialize filters to json syntax when calling report.getFIlters()

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#259]
Hi,

I'm currently getting the following error when calling getFilters for the report.  'Could not serialize filters to json syntax".  I'm not sure what the issue is since i'm not just trying to retrieve the filters?

Thanks,
Derek

**Comment by somriar** [comment]
hey,
can you please explain how you built your report? 
i am not getting a repro

**Comment by ali-hamud** [comment]
ping.

**Comment by ali-hamud** [comment]
closing as no response.
