### ISSUE TITLE
How to properly handle expire token?

### ISSUE THREAD

**Issue by darewreck54** [Microsoft/PowerBI-JavaScript#261]
Hi,

I was wondering what the best strategy for handling the case when the token expires.  When the token expires, the report will receive an error.  However, I'm not sure how you would recover from that since you have no knowledge of what action triggered the error.  

This seems like it would be a common occurrence.  If you leave the browser with the loaded report open for an hour, the token will expire and come back to it and try to click on the report or change a page, the error message will be triggered.  

You could technically implement book keeping of the operation it triggered and if it's a token issue, refresh the token and trigger the same operation again.  However, I wondered if there is another way to work around this.  

Also another question:

What happens when a user calls setPage() on a report object and the token stored in the report object is not valid.  Is an exception thrown by the setPage() method or is an "error" event triggered or is it both?  I also know a lot of these function like setPage() all can throw an exception so the question is do these bubble up to the "error" as well.  Referring to report.on("error")

Thanks,
Derek

**Comment by darewreck54** [comment]
What would be nice if the embed configuration took in a refresh token.  From there the client will try to refresh the token if it expires and try x amount of times.  If it fails, then send out an error.

**Comment by ali-hamud** [comment]
Hi @darewreck54 
please read this and let me know if you need more help.
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Refresh-token-using-JavaScript-SDK-example

We don't have Refresh Token support yet, what we have is:
You can use AAD refresh token to refersh your AAD token, and then call GenerateToken to get new EmbedToken with the refreshed AAD token.
