### ISSUE TITLE
403 Forbidden when embedding dashboard

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-JavaScript#264]
2.3.5 and Angular 4
Dashboard loads ok. The only things no events are working.
![image](https://user-images.githubusercontent.com/9266365/31381666-8c319ed2-adf8-11e7-9a31-1f5352b0ff1e.png)

Code is really simple:
![image](https://user-images.githubusercontent.com/9266365/31381738-c2effa68-adf8-11e7-9fdf-bf7600bfe65e.png)

**Comment by Goddak** [comment]
I have been trying to get `loaded`, `rendered` and `error` events for my dashboard embed too, they're just not being called.
