### ISSUE TITLE
Embedded dashboard is not loaded at all

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-JavaScript#265]
Guys, I have one chart which is based on Push data set
Out of 10 times, 4 times dashboard is not loaded at all and stuck at subscribe method:
![image](https://user-images.githubusercontent.com/9266365/31382837-4f0b0e72-adfc-11e7-8bad-8601d903cb9e.png)

**Comment by ZakharBorodin** [comment]
Could you, please, provide the ReqiestId header value of a failed request?
Thanks

**Comment by nicksav** [comment]
Strange but issues seems to go. The second issue which just disappear after sometime. This actually concerns me more:)
