### ISSUE TITLE
Colors on Power BI Service are not flowing to Power BI Embedded

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-JavaScript#266]
Guys, I am facing every day new issues:)
So the new one:
On Power BI Service I have a dashboard:
![image](https://user-images.githubusercontent.com/9266365/31418905-f9e0c42a-ae7b-11e7-8a06-6ab19efe3c9f.png)

And when embedding:
![image](https://user-images.githubusercontent.com/9266365/31418912-0279861c-ae7c-11e7-91be-3e9d310b18d1.png)

Why Yellow colors are done? Is there any limitations?

**Comment by ZakharBorodin** [comment]
The colors are selected randomly unless they are predefined. It is possibe so predefine colors in each visual for specific series.

**Comment by nicksav** [comment]
Strange but this somehow got resolved...
