### ISSUE TITLE
Dashboards - setAccessToken is not resolving the promis

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-JavaScript#268]
Reports are fine, dashboards - not. 
Please have a look

**Comment by ali-hamud** [comment]
setAccessToken is not implemented for dashboard.
marked as a bug.

**Comment by nicksav** [comment]
@ali-hamud Any ETA? We can't really go live without making sure Dashboard can be opened and live whole day on the wall screen.

**Comment by ArinaHantsis** [comment]
Hi @nicksav,
We'll add this item to our backlog and prioritize it high such that it can be picked up in the next couple of weeks.
Meanwhile a possible solution is to load dashboard through the SDK once in an hour ....

**Comment by Goddak** [comment]
Any update on this? I'm surprised the functionality was made available at all with the major flaw..

**Comment by ArinaHantsis** [comment]
Hey @Goddak,
Support for setting access token in a session should be publicly available around Dec 10th.
Please note that with the current solution the dashboard will be available through the entire session (whole day on the wall screen according to your description) but the tile data won't get refreshed automatically without a browser/app refresh. With setting access token every hour you'll be able to consume fresh updated data your entire session.

**Comment by Goddak** [comment]
@ArinaHantsis  - Sorry for my previous post, it was incomplete and potentially seemed rude.

Is there anywhere that upcoming releases are published to or is it just a case of watching the repo?

**Comment by ali-hamud** [comment]
Hi @Goddak,
You can always watch our github, or watch a specific issue.

In addition, we publish a monthly blog with updates.
https://powerbi.microsoft.com/en-us/blog/

**Comment by ali-hamud** [comment]
Issue fixed. please try.
