### ISSUE TITLE
powerbi doesen't fill the filled map with Google Chrome in German

### ISSUE THREAD

**Issue by ToastHawaii** [Microsoft/PowerBI-JavaScript#27]
I have a report with a filled map in it. If I publish this report with Azure Power BI Embedded in my Web-App then the map is not filled.
After I open the Console I can see that the call to the following URL gets a HTTP 400 back,

https://platform.bing.com/geo/spatial/v1/public/Geodata?key=AoW85FdF-eTJavFmWhZjaQ970kwG1FuainbyVSlP5HglkbhVVIFOyNwlaQxAIj-S&$format=json&SpatialFilter=GetBoundary(46.53919982910156,%206.583469867706299,%201,%20%27PopulatedPlace%27,%201,%200,%20%27de%27)&jsonp=jQuery220009483426731804667_1470914203199&_=1470914203355

I play around a little bit and I found out that the problem is that my language setting in Google Chrome is German "de". If I change the language from Google Chrome to Englisch (Vereinigte Staaten) "en-US" then it works.

Also I try to change the URL to the following URL and it works. (%20%27de%27 => %200,%20%27en-US%27,%20%27US%27)

https://platform.bing.com/geo/spatial/v1/public/Geodata?key=AoW85FdF-eTJavFmWhZjaQ970kwG1FuainbyVSlP5HglkbhVVIFOyNwlaQxAIj-S&$format=json&SpatialFilter=GetBoundary(46.53919982910156,%206.583469867706299,%201,%20%27PopulatedPlace%27,%201,%200,%20%27en-US%27,%20%27US%27)&jsonp=jQuery220009483426731804667_1470914203199&_=1470914203355

**Comment by wbreza** [comment]
Can you clarify what you mean by "...the map is not filled" ?  Please post a screenshot.

**Comment by ToastHawaii** [comment]
Here a screenshot from Google Chrome with the language setting German.
![googlechrome](https://cloud.githubusercontent.com/assets/1504145/17763721/dba581a4-651a-11e6-918d-052ded8ecde6.PNG)
it makes request like this: https://platform.bing.com/geo/spatial/v1/public/Geodata?key=AoW85FdF-eTJavFmWhZjaQ970kwG1FuainbyVSlP5HglkbhVVIFOyNwlaQxAIj-S&$format=json&SpatialFilter=GetBoundary(47.29603958129883, 9.185373306274414, 0, 'Postcode1', 1, 0, **'de'**)&jsonp=jQuery22005818110507342968_1471499914807&_=1471499917844

Here the same in Microsoft Edge, how it should look:
![microsoftedge](https://cloud.githubusercontent.com/assets/1504145/17763731/ec1ae36c-651a-11e6-923c-f2cbc8daa112.PNG)
it makes request like this: https://platform.bing.com/geo/spatial/v1/public/Geodata?key=AoW85FdF-eTJavFmWhZjaQ970kwG1FuainbyVSlP5HglkbhVVIFOyNwlaQxAIj-S&$format=json&SpatialFilter=GetBoundary(47.06380081176758, 9.041706085205078, 0, 'Postcode1', 1, 0, **'de-CH', 'CH'**)&jsonp=jQuery22005964272729953448_1471500121031&_=1471500122156

**Comment by wbreza** [comment]
Thanks for sharing.  This issue is unfortunately outside the scope of our JavaScript SDK and looks like a potential issue with the visual itself.

Please visit https://powerbi.microsoft.com/en-us/support/ to find out more information for getting support for this particular issue.
