### ISSUE TITLE
TileClick for some visuals returns strange PageName

### ISSUE THREAD

**Issue by nicksav** [Microsoft/PowerBI-JavaScript#270]
We are using TileClick to navigate back to the report from where the Tile was pined. 
Most of the tiles provide a correct Page Name to point to the report, but some return something like this:
ReportSectionf0f01d691cae22057804 instead of the correct PageName

Any idea?
Thanks
Nick

**Comment by ali-hamud** [comment]
Hi @nicksav 
It's not a strange name.
page names changed to have a unique random number (GUID style).
so it's by design.
