### ISSUE TITLE
Loading dashboards and reports within an electron browserWindow fails if webSecurity is disabled.

### ISSUE THREAD

**Issue by JuhaOl** [Microsoft/PowerBI-JavaScript#271]
Repors and Dashboards does not load when opened in Webview when webview has setting disablewebsecurity enabled.

Tiles are opened correctly.

**Comment by naknode** [comment]
Try in your browser's incognito mode to see if a Browser extension is conflicting with it.

**Comment by ali-hamud** [comment]
Hi,
do you mean android Webview?
do you see errors you can share?

last question: how do you embed in Webview?
do you set the source of WebView to an html with div element and use powerbi-client sdk to embed?

Thanks,
Ali Hamud

**Comment by JuhaOl** [comment]
Problem is with Electron and Cromium webview. Using powerbi.js and angular-powerbi.js. Reports and Dashboards loads normally when disablewebsecurity is disabled but fails when it is enabled. 

No specific error message is displayed. onEmbedded function is not launched when trying to load report or dashboard, but tiles loads fine.

**Comment by Goddak** [comment]
@JuhaOl - What was your solution for using a webview? I think I have the same issue.

**Comment by JuhaOl** [comment]
Developing Digital Signage project to get PowerBI reports into DS displays. 

Now we have to use separate settings in DS player when it has to show  PowerBI reports (web security enabled) and it restricts other content that can be used in DS displays.

**Comment by redders6600** [comment]
We're also having this issue. Can I suggest the title is changed to:

> Loading dashboards within an electron browserWindow fails if webSecurity is disabled.

**Comment by JuhaOl** [comment]
With latest updates in PowerBi - Now loading tiles fails also with electron Webview. Previously only reports and dashboards failed.

Checked headers of failing request/response: 
Request URL:https://wabi-west-europe-redirect.analysis.windows.net/metadata/cluster 
Request Method:GET
Status Code:403 Forbidden

Seems that Authorization:Bearer token is not passed with request when disablewebsecurity parameter is present in webview.
Referer is: https://app.powerbi.com/tileEmbed?dashboardId=XXX&dashboardId=XXX&tileId=YYY&tileId=YYY

**Comment by JuhaOl** [comment]
After few days of intensive debugging I figured this out!

There is a feature (or bug) in Microsoft .js code. When powerbi iframe window has a parent available, accessToken is fetched from parent (which is 'undefined' by default), even if there is token available in requests embed configuration. And when web security is disabled, parent window is available for iframe that displays powerbi content (even if iframe is sandboxed). When web security is enabled, parent is not available from iframe and embed configuration token is used.

This feature affects also Crome browser when it is launched without web security - not only electron webview.

To bypass this issue you must assign token also to window that opens powerbi reports. In some cases you might have to add token also to windows parent...

In angular you can do it like this:
`$window.powerBIAccessToken = accessToken;`
`try{`
`    if ($window.parent)`
`        $window.parent.powerBIAccessToken = accessToken;`
`    } catch (e) {}`

**Comment by redders6600** [comment]
@JuhaOl thanks for sharing this - good detective skills!

**Comment by ondrejspilka** [comment]
Hey man, you saved me couple of hours. I figured it out to the point of missing bearer!
Thanks a lot!
