### ISSUE TITLE
Handling report click event

### ISSUE THREAD

**Issue by snobu** [Microsoft/PowerBI-JavaScript#273]
I'm not able to find a simple way to bind to a report click event, to be precise I can't make it fire such an event.

According to [this Wiki page](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters#keeping-your-application-in-sync-with-the-report), a `filtersApplied` event is in the works. Is there an ETA for it? It doesn't look like it's implemented yet:

```javascript
dashboard.on("filtersApplied", function(event) {
    console.log(event.detail);
 });

powerbi.min.js:2 Uncaught Error: eventName is must be one of
loaded,saved,rendered,saveAsTriggered,error,dataSelected,tileClicked,error.
You passed: filtersApplied
    at e.t.on (powerbi.min.js:2)
    at <anonymous>:2:11
```

Now, I could get around that by listening to *click* events on the `div` wrapper around the report and calling `getFilters()`, then compare current filters to previous set of filters (not very elegant but still fine).

![My DOM](https://i.imgur.com/YeboiU1.png)

However binding to the report `div` does not work:
```javascript
$('#dashboardDiv').click(event => {
   console.log(event);
});

// Has no effect
```

This probably has to do with iframes and same origin policy.

My question is very simple, how do I get an event to fire when the report is clicked or filters change?

**Comment by ali-hamud** [comment]
filtersApplied has lower priority between other features.
But you can use another event we have: 'rendered'
'rendered' event will be raised each time the visualizations change, and this could tell about a filter change.
please let me know if it's good enough.

Thanks,
Ali Hamud
