### ISSUE TITLE
Print issue for  Page size type custom

### ISSUE THREAD

**Issue by prasy14** [Microsoft/PowerBI-JavaScript#274]
Hello All,

My Power BI report page size type is custom and size is 1600 *1400. When i use the Print code below my report is not printing fully(Chopping out the edges).
Can you please suggest me if there any way to shrink report and print.

`// Get a reference to the embedded report HTML element`      
        `var embedContainer = $('#embedContainer')[0]; `
`// Get a reference to the embedded report.`
        `report = powerbi.get(embedContainer);`
` // Trigger the print dialog for your browser.`
    `report.print()   `
 `.then(function (result) {        Log.log(result);    })`    
`.catch(function (errors) {        Log.log(errors);    });`

![image](https://user-images.githubusercontent.com/31737930/32121548-03dbef02-bb2b-11e7-9838-f7b3c1626390.png)

**Comment by cmarquis** [comment]
I am having similar issues. We have been testing with reports set at 16:9 and 4:3 and it always seems to cut off some portion of the report using the print function.

**Comment by ali-hamud** [comment]
are you printing in portrait of landscape?
please note that the print function we expose uses the browser print function on the iframe.
so, it actually depends in your printer settings.

please give us more details about: browser, printer settings, and so..

**Comment by ali-hamud** [comment]
closing as no response.
