### ISSUE TITLE
Unable to Clone or Copy the Power BI Report

### ISSUE THREAD

**Issue by sammicrosoft** [Microsoft/PowerBI-JavaScript#275]
Dear All,

 I had written the below code to clone the Power BI report , But I don't find the luck to clone the report . Can any one help me in knowing what's wrong in my below code

**Code:** 
function CopyReport(reportId, Name, Dataset) {
    debugger;
    var deferred = $.ajax({
        url: "https://api.powerbi.com/v1.0/myorg/reports/" + reportId + "/Clone",
        type: "POST",
        headers: {
            "Authorization": "Bearer " + accessToken
        },
       // ContentType: "application/json",
        data: { Name: Name},
        //data: { name: Name, targetWorkspaceId: Dataset },
        success: function (responseData) {
            cache.write(responseData, "Copy report")
        },
        error: function (responseData) {
            debugger;
            cache.write(responseData, "Copy report")
        }
    });
    return deferred.promise();
}

**Error**:
{"error":{"code":"PowerBINotAuthorizedException","pbi.error":{"code":"PowerBINotAuthorizedException","parameters":{},"details":[],"exceptionCulprit":1}}}

**Comment by ali-hamud** [comment]
in data: { Name: Name},
try small n.

and please make sure your registered AAD application has Reports.Write.All permisssion.

If this didn't help, please give a request Id of the failing request. you can find it in request headers.
Thanks,
Ali Hamud
