### ISSUE TITLE
Vertical Orientation Slicer Not triggering Data Selection event in Power BI embedded report

### ISSUE THREAD

**Issue by Talark** [Microsoft/PowerBI-JavaScript#278]
The Vertical orientation Slicer was triggering the data select event in the embedded report in our application normally, but suddenly it stopped working. You can also test that in Microsoft's Power BI embedded sample https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html# 
We tried to change the orientation of slicer to horizontal and the event triggers and works, but we need to have it vertical as checkbox.

**Comment by ali-hamud** [comment]
Hi @Talark,
Thank you for reporting this issue.
We will repro the problem, and fix it ASAP.

**Comment by donquijotedelamancha** [comment]
Hi @Talark , @ali-hamud 
In case it helps, same issue here, the dataSelected event doesn't fire for vertical oriented slicer but does fire for horizontal oriented slicer. This is breaking prod app for us. Please fix ASAP!

**Comment by ArinaHantsis** [comment]
Hi @Talark,
We are actively working on a fix and expect it to get deployed later this week, will update once it gets resolved.

**Comment by Talark** [comment]
Hi @donquijotedelamancha 
I didn't try generating the report from older Power BI Desktop version. 
If it helps in your case, I changed it temporarily to Chiclet slicer (imported it from the store) and played with its properties a bit to fit our report, it catches the dataSelected event, looks and works fine.

**Comment by donquijotedelamancha** [comment]
Hi @Talark  
Thanks a lot for the suggestion! The functionality that this broke is quite important for my app so your alternative might save me until the solution for the bug is deployed which I hope is asap!

**Comment by donquijotedelamancha** [comment]
Hi @ArinaHantsis 
Do you have an update on the expected time for deployment on this fix ? Very much looking forward to it. Thanks!

**Comment by ZoltanVago** [comment]
Hello,
Can we expect the fix early this week? We were very close to launching our new product in Power BI Embedded last week, but this bug prevented that. Unfortunately, due to design and functionality considerations we cannot go out without the vertical slicers.
Thanks!

**Comment by donquijotedelamancha** [comment]
For what is worth, this has started working for me again in the last minutes
