### ISSUE TITLE
Can't run in vue2.0 right?

### ISSUE THREAD

**Issue by sparkxxxxxx** [Microsoft/PowerBI-JavaScript#280]
I use power-client in my vue2.0 project. But generate some bugs.For example, I can't use powerBI.embed function... 

![image](https://user-images.githubusercontent.com/4017852/32551423-6cee2a7e-c4cb-11e7-9f02-4a8025462fdb.png)

![image](https://user-images.githubusercontent.com/4017852/32551446-7fe08f00-c4cb-11e7-80b3-cc1fc6587c97.png)

**Comment by eliashdezr** [comment]
I think you have an error on your code, shouldn't be like this the data object?

```
data () {
  return {
     msg: 'something',
     powerBi: powerBi
  }
}
```

And then you can call it like this: `this.powerBi.embed`

**Comment by ali-hamud** [comment]
Hi @sparkxxxxxx , please let us know if what @eliashdezr suggested helps.

**Comment by sparkxxxxxx** [comment]
@ali-hamud  Sorry to reply you later. I find the reason that mounting powerbi to window object. It works with below code.

![qq 20171114200618](https://user-images.githubusercontent.com/4017852/32779091-6a8db848-c977-11e7-925f-5e3411b7c500.png)
