### ISSUE TITLE
How do I get width and height for a report?

### ISSUE THREAD

**Issue by snobu** [Microsoft/PowerBI-JavaScript#281]
How do I get the width and height for a report that I’m about to embed?

The `iframe` produced by the SDK is `style="width:100%;height:100%;"` which really does nothing good for dimensions. If I don’t specify width and height on the embed DIV then it looks all kinds of wrong, for example: 
![image](https://user-images.githubusercontent.com/6472374/32553061-7ea0b584-c49e-11e7-9d84-dbce59dd58c6.png)

What i'm hoping for is an API call (either from JavaScript or from my backend calling into `api.powerbi.com`) that would return dashboard size, or **Page size** (again, hoping these two things are one and the same):

![image](https://user-images.githubusercontent.com/6472374/32553543-e04a1126-c49f-11e7-98aa-a57353743508.png)

**Comment by ali-hamud** [comment]
We don't have a function which can be used to get Page width and Height yet.
We are working on this.

but, IMO, the report should fit to the div element you have, not the opposite.
so, just save the report as FitToPage, have larger div element in your HTML, and embed the report to it.
the report should Fit to the area it has.

**Comment by snobu** [comment]
> but, IMO, the report should fit to the div element you have, not the opposite.
Yes, but i'm trying to avoid scroll bars at all costs. I'd rather have browser scroll bars than iframe scroll bars.

**Comment by ali-hamud** [comment]
for dashboard you will need to use
 pageView?: models.PageView

look here:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details

**Comment by snobu** [comment]
Thanks for that, i do have some progress here:
```
var config = {
        type: 'dashboard',
        ...
        pageView: 'fitToWidth'
};
```

This fits the report nicely in width, but i still have to hardcode the `height` in beforehand, since i don't know what the right height should be for a particular dashboard, lots of gray padding may happen:

![image](https://user-images.githubusercontent.com/6472374/32954850-f2c0a616-cbbc-11e7-8a82-d7e743de38f5.png)

Since the height is a hardcoded value, it may happen the report fits in width just right, but there's not enough height and gets clipped, so i'm more or less back o the drawing board...

How is everyone else doing this? I mean, if it's just me i'll definitely try to rethink my approach.

**Comment by hexeh** [comment]
@snobu 
This information may be helpfull:

While embedding we define style properties for parent div of iframe as following:

```
width: 100%;
height: 0;
padding-bottom: 100 * reversed_page_aspect_ratio%;
```
For default page sizing (1280 x 720) padding-bottom is 100 * (9 / 16) = 56.25%

Unfortunately, aspect ratio should be saved on page before embedding because there is no way to get this value as I can see .

**Comment by ali-hamud** [comment]
Hi,
Just a summary before closing the issue:
When you want to embed a dashboard, you can pass one of these three values to pageView settings parameter:
"actualSize", "fitToWidth", "oneColumn"

Example:
actualSize:
![image](https://user-images.githubusercontent.com/23071967/34818626-0b50b7de-f6c4-11e7-9917-c7a3958aa050.png)

fitToWidth:
![image](https://user-images.githubusercontent.com/23071967/34818642-18cc7b96-f6c4-11e7-96d0-aacdf81a595d.png)

oneColumn:
![image](https://user-images.githubusercontent.com/23071967/34818679-34991064-f6c4-11e7-9a38-f819a9d1ce7b.png)

If you want to embed reports with different sizes, you have more flexibility. please read here:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Custom-Layout
