### ISSUE TITLE
Can i use powerbi-client on Power BI Report Server?

### ISSUE THREAD

**Issue by Restry** [Microsoft/PowerBI-JavaScript#282]
**when i get a iframe on my web page after powerbi.embed. 
i can get a  object name is firstReport, this object have property : refresh**
```

var models = window['powerbi-client'].models;
 
// We give All permissions to demonstrate switching between View and Edit mode and saving report.
var permissions = models.Permissions.All;
 
// Embed configuration used to describe the what and how to embed.
// This object is used when calling powerbi.embed.
// This also includes settings and options such as filters.
// You can find more information at https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details.
var config= {
    type: 'report',
    tokenType: models.TokenType.Embed,
    accessToken: 'any',
    embedUrl: 'http://192.168.8.101:7001/reports/powerbi/txncountblcntoday?rs:embed=true',
    id: '7165c156-08bb-42b1-906b-70db22afd3bf',
    permissions: permissions,
    settings: {
        filterPaneEnabled: true,
        navContentPaneEnabled: true
    }
};
 
// Get a reference to the embedded report HTML element
var embedContainer = $('#embedContainer')[0];
 
// Embed the report and display it within the div container.
window.firstReport = powerbi.embed(embedContainer, config);

```

**but if i'm use firstReport.refresh(); i'll get the error** 

`firstReport.refresh()
txncountblcntoday?rs:embed=true:1 (WEB_PAGE context) Lazy require of webstore.binding did not set the binding field
txncountblcntoday?rs:embed=true:1 (WEB_PAGE context) Lazy require of runtime.binding did not set the binding field
6:8023/#:1 Previous API instantiation failed.
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
extensions::webstore:7 Uncaught Natives disabled
(anonymous) @ extensions::webstore:7
txncountblcntoday?rs:embed=true:1 (WEB_PAGE context) extensions::event_bindings:8: Uncaught Natives disabled{<stack trace unavailable>}
txncountblcntoday?rs:embed=true:1 (WEB_PAGE context) extensions::binding:5: Uncaught TypeError: Cannot read property 'Event' of undefined{TypeError: Cannot read property 'Event' of undefined
    at extensions::binding:5:38
    at extensions::runtime:7:28}
extensions::runtime:7 Uncaught TypeError: Cannot read property 'Binding' of undefined
    at VM7212 extensions::runtime:7`

**Comment by eliashdezr** [comment]
My guess would be that the Report Server has its own JavaScript library.  You can use the event listeners in the Chrome Dev tool to see from what JavaScript files they are attached

**Comment by Restry** [comment]
@eliashdezr  thanks for you reply ,  but Dev tool it's really a hard way to find i want . do you know where i can find the Report Server JS source code or some api document ? 
 i just want to achieve manually refresh the embedded report view

**Comment by ali-hamud** [comment]
Hi,
Power BI Report Server is not supported in this sdk.
let me update if I have something which can help you.

**Comment by Restry** [comment]
@ali-hamud  thanks so much . waiting for your update :)  .

**Comment by Li-Yanzhi** [comment]
@ali-hamud Any update for this issue? we are waiting this feature too!

**Comment by ali-hamud** [comment]
Hi @Li-Yanzhi,
can you please ask in this forum: 
https://community.powerbi.com/t5/Report-Server/bd-p/ReportServer

I am closing this issue because it's not relevant to this library.
Please re-open the issue if you didn't get an answer there.
