### ISSUE TITLE
Refresh Token

### ISSUE THREAD

**Issue by karangop** [Microsoft/PowerBI-JavaScript#283]
Hi, i saw the wiki about "Refresh token", but i don´t find generateEmbedToken() function in the all project!

https://github.com/Microsoft/PowerBI-JavaScript/wiki/Refresh-token-using-JavaScript-SDK-example

I have a lot questions!!
I have a token generated from this page:
https://github.com/guyinacube/Embed-API-Sample

But, once its ok...i put the token in proyect javascript! Until here all ok.

After i need that the token refresh automatically, but i dont know how??

Anyway, I need show report in mobile app of way responsive and with only one account power bi pro.

Hopefully, i will have a lot answer or advice!!

Thank you very much!!
Regards,

Karina Gonzalez

**Comment by ali-hamud** [comment]
let me know if this helps:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Refresh-token-using-JavaScript-SDK-example

**Comment by karangop** [comment]
Hi, no a lot!!
Because i don´t found generateEmbedToken function in the project!
Then, I am a little confused of how make??

thanks!
![image](https://user-images.githubusercontent.com/8389031/32611517-aed7c0e8-c544-11e7-9e9e-b6167df0f8c0.png)

**Comment by ali-hamud** [comment]
yeah this method is a method you should implement.
basically, this method should do an ajax call to your back end to get a new token.

**Comment by karangop** [comment]
Sorry, but i don´t know how!
Dou have an example that you can share? Please.
Thank you for your time!!

**Comment by ali-hamud** [comment]
Hi @karangop 
you should first have a service with API endpoint which generates an embed token for you.
The code you found in the sample above, you should put it in a service.

an example of that is:
https://github.com/Microsoft/PowerBI-Developer-Samples/tree/master/App Owns Data

once you have a service up and running, just do an ajax call when you know the token is expired (as explained in the wiki link I sent in previous comments.)

to do an ajax call, you may use jquery:
http://api.jquery.com/jquery.ajax/

**Comment by karangop** [comment]
Thank you very much for your answer!!
I gonna make the ajax call!!

**Comment by ali-hamud** [comment]
You should call GenerateToken in your service (BE side).
Otherwise you will have to pass your bearer token to FE side which is not secure.
