### ISSUE TITLE
Power BI client does not work well in Typescript or Angular?

### ISSUE THREAD

**Issue by zhll2046** [Microsoft/PowerBI-JavaScript#286]
We've received some users reporting issues about Power BI client. The issues are typically in Typescript and Angular. In Javascript it works all well.
See below links.
['getPages' does not exist on type 'Embed'](https://community.powerbi.com/t5/Developer/powerbi-client-2-4-2/td-p/296278)
[Property 'getFilters' does not exist on type 'Embed'](https://community.powerbi.com/t5/Developer/Some-API-functions-doesn-t-work-using-TypeScipt/m-p/302661#M8922)
@sirui-sun 
@craigb 
@druttka

**Comment by zhll2046** [comment]
@ali-hamud

**Comment by ali-hamud** [comment]
Hi,
classes Report, Dashboard, Tile and QnA inherit from class Embed.
when you call powerbi.embed, you will get Embed object.
you can downcast this object to Report if you called powerbi.embed with type="report".
similar to Dashboard, Tile and QnA.

Report object has the methods getPages and getFilters you need.
