### ISSUE TITLE
How can I render My own report with this feature

### ISSUE THREAD

**Issue by dead8171** [Microsoft/PowerBI-JavaScript#288]
How can I use my own report with this feature?? How can I pass custom filters with this ??
How can I redirect certain data click onto other page??

**Comment by ali-hamud** [comment]
If you need a full E2E solution which works with your reports, please follow this sample:
https://github.com/Microsoft/PowerBI-developer-samples

**Comment by dead8171** [comment]
@ali-hamud How can I pass my filters in that report, I mean to say how can I pass a filter in that report that will sort the report from start and end date??

**Comment by dead8171** [comment]
@ali-hamud cant I embed My own report with this?

**Comment by dead8171** [comment]
I cant seem to find node_modules directory under the directories that are listed in the github source, Please tell me how can I look or download those files??

**Comment by ali-hamud** [comment]
node_modules are a folder which contains npm packages after running npm install in project folder.

please follow this live sample to see code samples about how to embed report and set filters and so on:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html

please follow our github wiki to see the embed configurations we give.

**Comment by dead8171** [comment]
@ali-hamud How to run npm install on windows can provide with some links here I have no knowledge of npm.

**Comment by dead8171** [comment]
@ali-hamud When I pass this in nuget command line in visual studios 'Install-Package Microsoft.PowerBI.JavaScript'

I get this error:-

Install-Package : Project 'Default' is not found.
At line:1 char:1
+ Install-Package Microsoft.PowerBI.JavaScript
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Default:String) [Install-Package], ItemNotFoundException
    + FullyQualifiedErrorId : NuGetProjectNotFound,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by dead8171** [comment]
@ali-hamud How can I set my own report here do I need to change something in the files to do that?? 
Can you help me on this??

**Comment by dead8171** [comment]
Are there any more functionalities that can capture events with tooltip and can redirect a certain click onto different page??

**Comment by ali-hamud** [comment]
- Project 'Default' is not found.
You are trying to install a nuget package to a project you don't have (deleted or something).
You can select from the projects dropdown to which project you want to install.

- How can I set my own report here..
"here"?
You can embed your own reports of course.
You need to generate tokens for these reports using GenerateToken API
https://msdn.microsoft.com/en-us/library/mt784614.aspx

You can use the E2E samples we have:
https://github.com/Microsoft/PowerBI-developer-samples

Are there any more functionalities that can capture events with tooltip and can redirect a certain click onto different page??
- You can listen on user clicks on data points using the dataSelected event.
usage: report.on("dataSelected", event => {})
We don't have API which gives you tooltip text.
