### ISSUE TITLE
Multipages reports, export to pdf and other issues

### ISSUE THREAD

**Issue by rockking15** [Microsoft/PowerBI-JavaScript#290]
Hi guys! Thanks for this great library PowerBI-Javascript. I used it and I have a lot of questions because of customer needs.

1. I have a big report with a scroll bar on the right side. And when I use report.print() I see only one part of my report (like screen browser window). How can I print full report, it possible?
2. I have report with 10 tabs. Is it possible to print all of them?
3. Is it possible to export reports to pdf/ word/ powerpoint/ excel by JS SDK or other sdks?
4. Could I add my custom styles to PowerBI iframe?
5. Could I export reports to PowerPoint via sdk?

I use an Azure web app, JS SDK, c# SDK and power bi web version by API.
Thanks for your answers.

**Comment by somriar** [comment]
hey,
i got some answers for you:
1. for now the print option is is just a basic print of the iframe content and we don't have any optimizations on it.
2. this is not possible with one command. you can use  report.setPage() to navigate between pages and print them one by one.
3. not possible
4. not possible
5. not possible  

I hope we can be more helpful on your next questions :/

**Comment by ali-hamud** [comment]
related issue.
https://github.com/Microsoft/PowerBI-JavaScript/issues/199
