### ISSUE TITLE
-webkit prefixing for older browsers

### ISSUE THREAD

**Issue by Goddak** [Microsoft/PowerBI-JavaScript#295]
I am currently embedding a dashboard that will be loaded using various devices, one of the devices is using an old version of the Android browser and it cannot be updated.

On this device the dashboard displays slightly to the right and down.
![image](https://user-images.githubusercontent.com/12832288/33607696-d2395f0e-d9b9-11e7-8898-0f05e4a1c3c1.png)

I have identified that the reason is due to a lack of -webkit prefixing and the browser falling back to the default (This is the same for the animation but I'm not crying about that :P).
![image](https://user-images.githubusercontent.com/12832288/33607795-31ca3916-d9ba-11e7-9611-2915a88d445c.png)

By simply adding the -webkit prefix the problem is solved (this can probably be done as part of a build process)
![image](https://user-images.githubusercontent.com/12832288/33607890-755393a8-d9ba-11e7-928f-21df6b67812c.png)
![image](https://user-images.githubusercontent.com/12832288/33607898-7bf39474-d9ba-11e7-86b4-a2059a83cf4a.png)

**Comment by diklab** [comment]
Hi @Goddak,
What is the browser version you are using?

Thanks,
Dikla

**Comment by Goddak** [comment]
@diklab The browser that this issue specifically is observed on is Android browser 4.4.2

**Comment by somriar** [comment]
hey, 
i'm afraid we do not support this browser.
The supported browsers for powerbi can be found here:
https://docs.microsoft.com/en-us/power-bi/service-browser-support

**Comment by Goddak** [comment]
Hey @somriar 

Thanks for your response, I hadn't actually looked at the list of supported browsers as I didn't actually consider this as a browser specific issue and had instead put it down as a prefixing issue at build time (seeing as this specific issue is fixed with a CSS prefix).
