### ISSUE TITLE
Print in Edge and IE bug

### ISSUE THREAD

**Issue by rockking15** [Microsoft/PowerBI-JavaScript#299]
When I want to print my chart in Edge - first time everything OK, but when I use report.print() at the second time without page reload I see additional Filters tab at the right hand, but I don`t need this!

In the IE 11 print is very bad unfortunatelly. I have one page chart. And when I want to print this chart in IE a have 3 separate pages with pieces of this chart.

In Chrome and Mozilla everything OK.

**Comment by diklab** [comment]
Thanks @rockking15 !
I will open a bug on this one.
