### ISSUE TITLE
How do I get a Token with javascript?

### ISSUE THREAD

**Issue by davidemoraschi** [Microsoft/PowerBI-JavaScript#3]
HI all,
thanks for publishing this one. I am trying to create a very simple web page but I don't know how to pass:

window.powerbi.accessToken = ??????????????

how do I get one. Is this the Access key I find in Azure portal? I don't think so....

thanks for your help
Davide

**Comment by wbreza** [comment]
Once you get your access key from the Power BI workspace collection created in Azure you need to construct a JWT token that is signed with you access key. More info regarding the app token flow can be found [here](https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-app-token-flow/).

Do not create and sign your tokens client side.  Never expose your azure access keys. These should be kept secret.

To create JWT tokens;

1. If using .NET, use the [Microsoft.PowerBI.Core](https://www.nuget.org/packages/Microsoft.PowerBI.Core/) Nuget package
2. If using other platforms construct a JWT token on your server and sign it with your access key

Here is a sample expired token:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ2ZXIiOiIwLjEuMCIsInR5cGUiOiJlbWJlZCIsIndjbiI6IlN1cHBvcnREZW1vIiwid2lkIjoiY2E2NzViMTktNmMzYy00MDAzLTg4MDgtMWM3ZGRjNmJkODA5IiwicmlkIjoiOTYyNDFmMGYtYWJhZS00ZWE5LWEwNjUtOTNiNDI4ZWRkYjE3IiwiaXNzIjoiUG93ZXJCSVNESyIsImF1ZCI6Imh0dHBzOi8vYW5hbHlzaXMud2luZG93cy5uZXQvcG93ZXJiaS9hcGkiLCJleHAiOjEzNjAwNDcwNTYsIm5iZiI6MTM2MDA0MzQ1Nn0.WzOQJW_0n7NLfsr7UelWwljAF2kDAYXZEevMwa4ODo8

**Include the following required claims:**
version: 0.1.0
type: embed
aud: https://analysis.windows.net/powerbi/api

**Replace the following claims with values from your workspace collection:**
wcn: Your workspace collection name created in azure
wid: Your workspace id within your collection
rid: Your Power BI report id that has been uploaded to your workspace

Ensure your JWT contains valid expiration claims:
nbf: Unix file time for not valid before
exp: Unix file time for token expiration

**Comment by mattmazzola** [comment]
Oh, Wallace responded right before me. Adding few more details below:

**"Is this the Access key I find in Azure portal?"**
No, it is not. As he said, do not expose your API key (aka Signing Key) from the portal. This must be kept secure otherwise someone else could use it to generate tokens which have access to your workspace collection.

**"how do I get one?"**
Sample code:
```
var embedToken = PowerBIToken.CreateReportEmbedToken(this.workspaceCollection, this.workspaceId, Guid.Parse(report.Id));
accessToken = embedToken.Generate(this.signingKey);
```

**Comment by davidemoraschi** [comment]
Excellent! Thanks Wallace


*Davide Moraschi*
*http://moraschi.com* <http://moraschi.com/>
*https://www.amazon.com/author/davidem*
<https://www.amazon.com/gp/r.html?C=Z9SQXHR9LXA4&R=3F1OKNQ7SW5BO&T=C&U=https%3A%2F%2Fwww.amazon.com%2Fauthor%2Fdavidem%3Fref_%3Dpe_1724030_132998060&A=TLR48N5APERG7WGZZMPWR27LJHIA&H=3MNX5XZ2AQAISMXHAAWJOVW9AR8A&ref_=pe_1724030_132998060>
Skype: davide.moraschi (Sevilla)
US Landline: (347) 983-0274
Mobile: +34 690063666
Whatsapp: +34 658055466

**Comment by Mike-Honey** [comment]
If this info is still relevant, can you add it to the wiki?  If it isn't relevant any more, can you add something relevant to the wiki?

**Comment by sabhishek0794** [comment]
how to get access key of user in Azure AD

**Comment by PhatHoang21** [comment]
Is there any way to get token with .Net Core project? I couldn't resolve "Microsoft.PowerBI.Api" and "Microsoft.IdentityModel.Clients.ActiveDirectory" packages in .Net Core project. It requires .net framework.
