### ISSUE TITLE
"navigationUrl" is null in "event.detail"  on tileClicked event handler.

### ISSUE THREAD

**Issue by shcodes11** [Microsoft/PowerBI-JavaScript#300]
I'm embedding dashboards in my app and would like to navigate to the 'navigationUrl' when a tile is clicked. However, if the dashboard tile is configured to open a different dashboard in the same workspace/group (/dashboard/<dashboardid>) which can be configured as below

![image](https://user-images.githubusercontent.com/2554565/33746343-67103338-db71-11e7-963f-fe4711671d43.png)

on 'tileClicked' event handler doesn't provide information about the new dashboard to navigate to. 
e.g. event.detail json when the tileClicked handler gets invoked.

Event:{
  "event": "TileClick",
  "reportEmbedUrl": "",
  "navigationUrl": null,
  "tileId": "65c98931-ab17-446f-8b0f-f598c6d378972",
  "pageName": "ReportSection"
}

As you can notice, the navigationUrl is null and what I really need here to navigate is the dashboardid to navigate to.

Can you help?

**Comment by ranbreuer** [comment]
Hey
This issue was a regression in Tile Embed functionality that has been fixed in latest deployments.
