### ISSUE TITLE
How to do use visual filter?

### ISSUE THREAD

**Issue by yeonseokhan** [Microsoft/PowerBI-JavaScript#301]
I want use visual filter but, now can not use visual functions.
if not support visual functions,  I want to know the support plan about visual functions.
and my purpose is, want to control slicer filter or want to detect changed slicer property

**Comment by diklab** [comment]
Hi @yeonseokhan,
We do have visual filters on visuals in report, you can try them out here:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html#
Click on the 'Embed sample report', in step number 2 click on the 'Run' button to load the sample report.
Now you can move to step number 3 and try to use the visual filters functions.

Thanks,
Dikla
