### ISSUE TITLE
How to get the data of a page in the embed report?

### ISSUE THREAD

**Issue by gui0704** [Microsoft/PowerBI-JavaScript#305]
I have embeded a report in my html container, and I want to get the data of the report(or the data of one page in the report),how to get the data in Power BI Javascript API?

**Comment by somriar** [comment]
hey,
you can use report.getPages to get the pages pf the report

report.getPages()
    .then(function (pages) {
        pages.forEach(function(page) {
            var log = page.name + " - " + page.displayName;
            Log.logText(log);
        });
    })
    .catch(function (error) {
        Log.log(error);
    });

you can see an example on:
https://microsoft.github.io/PowerBI-JavaScript/demo/v2-demo/index.html
on the link you can embed a report and go to interact -> Get Pages

**Comment by gui0704** [comment]
yes, this method can get the page, and use the page.getVisuals().then() can get visual desciptor , but this can't get the data of the visual, just the visual name and layout info, and what I want is the detail datapoint of the visual, such as category and value; if I use the event on  'dataSelected', I can get the data of the cilcked element, but this is not enough, I also need the data which is not clicked, is the javascript  sdk providing another api to get it?
