### ISSUE TITLE
Datapoint Missing

### ISSUE THREAD

**Issue by shahabaz** [Microsoft/PowerBI-JavaScript#310]
I am using the code for Custom Command. But I am not able to see the "Datapoint" in the object when it is triggered need help. 

Find the JSON generated when the I click my custom trigger

![image](https://user-images.githubusercontent.com/4548913/34862809-449f0a58-f792-11e7-8ea1-3b5c55312c71.png)

**Comment by ali-hamud** [comment]
Hi,
I assume you are getting this event when clicking on options menu "...".
Options menu will not give you the data points. context menu will give you the selected data points on right click.

**Comment by shahabaz** [comment]
Hey thanks, Man That clears something now. The issue with the context menu is that I am only getting only one data point on which the cursor is being right-clicked. How do I get all the data which comes under show data menu?

**Comment by shahabaz** [comment]
Hey thanks, Man That clears something now. The issue with the context menu is that I am only getting only one data point on which the cursor is being right-clicked. How do I get all the data which comes under show data menu?

**Comment by ali-hamud** [comment]
Hi @shahabaz 
We don't have this feature by now. please open an idea in https://ideas.powerbi.com/ in order to give this feature higher priority.

**Comment by shahabaz** [comment]
Okay Thanks, Will do it. Appreciate your effort.
