### ISSUE TITLE
Not able to run my report in demo page

### ISSUE THREAD

**Issue by mrgoos** [Microsoft/PowerBI-JavaScript#316]
Hi,
I'm using the `Microsoft Power BI Embedded Sample` and putting my `Embed Token` and my `Report Id`.
When clicking `Run` I see an error in the console log:
`GET https://wabi-us-north-central-redirect.analysis.windows.net/explore/reports/72590f90-5a65-400e-9f73-93482a463bc4/modelsAndExploration 401 (Unauthorized)`
Followed by:
`reportembed.externals.bundle.min.js:593 TypeError: Cannot read property 'code' of undefined`.
Our tenant is indeed located in west europe.
Does that mean that I cannot demo my report there?

Thanks.

**Comment by ali-hamud** [comment]
1) What is the embed url you use? how did you get it?
2) pay attention you need to select "Embed Token" as your token type.

**Comment by mrgoos** [comment]
@ali-hamud -
This is the URL that I use:
`https://app.powerbi.com/reportEmbed?reportId=72590f90-5a65-400e-9f73-93482a463bc4&groupId=7e9e8639-e5e3-4a63-9f68-98664c73472c`.
I got from the power-bi app by going to File->Embed in sharepoint online. If there's a better way please LMK.
![image](https://user-images.githubusercontent.com/2561935/35674038-0e281874-074c-11e8-8fed-9df3a8d48ba0.png)

2. Selected.

Does that help?

**Comment by ali-hamud** [comment]
and how did you generate the embed token?
Did you called the "/GenerateToken" API?

**Comment by acomito** [comment]
I am having the same issue. I'm getting a token back (I think), although I'm not passing in any credentials really. It would be great if somebody can take 20 minutes to just put together the code snippet needed to get an embed token. I see question about this all over the internet and the documentation isn't clear, or uses c, and it's been a frustrating experience to just get a powerbi report to show up on the screen.

Here is where I'm at:

```
import powerbi from 'powerbi-api';



const generateEmbedTokenFromAPI = async (reportId, groupId) => {
        // not clear on if/when I should be using 
        // my client secret and client id... is there a 
        // new powerbi() instance I should be feeding them into?
        let token = await powerbi.PowerBIToken.createReportEmbedToken('My Dashboards', groupId, reportId);
        console.log('=========> token')
        console.log(token) // logs what I believe is the  PowerBIToken
        
         var jwt = await token.generate('{AccessKey}');
        console.log('=========> jwt')
        console.log(jwt) // logs what looks like a JWT token

        return jwt; // return the token, use it on the client, get a 403 error.

    }
});
```

**Comment by mrgoos** [comment]
@ali-hamud - Yes, I do use the `/GenerateToken` API.
I have read everything that's in this [article](https://msdn.microsoft.com/en-us/library/mt784614.aspx).
I have also created an Access token on each request using python SDK currently and everything passes.
I can send you the embed token over email if you want or if you have another way to check this, please advise.

I think that the tenant might be hard coded somewhere in the demo page, is that possible?

**Comment by ali-hamud** [comment]
Hi @acomito,
I see that you use powerbi-api npm package which works only with the old embed scenario (Power BI Workspace Collection in Azure). Do you use the old embed scenario?

Hi @mrgoos,
we will check this and post.

**Comment by mrgoos** [comment]
Thanks a lot @ali-hamud!

**Comment by ali-hamud** [comment]
Hi @mrgoos,
Can you give a request ID of a failure request? this will help me investigating the failure.

**Comment by mrgoos** [comment]
Yes.
This is it: `RequestId:e416e20e-e481-9681-443d-01be08df7751` from `Date:Sun, 04 Feb 2018 11:03:02 GMT`.
There was also this one earlier: `RequestId:7ffe6dfa-df58-a9d1-4b2c-62f8449af0be` from `Date:Sun, 04 Feb 2018 10:49:47 GMT`.
Thanks @ali-hamud.

**Comment by ali-hamud** [comment]
Hi @mrgoos 
can you check if report embed makes a call for "/metadata/cluster"?
what is the request Id for this call?

**Comment by mrgoos** [comment]
I have refreshed the page and now, I do see that it fails in `/metadata/cluster`.
`Request URL:https://wabi-west-europe-redirect.analysis.windows.net/metadata/cluster`
`RequestId:b5399140-1ff5-15a7-6b06-d35fbec67f62`
Still forbidden.

The scenario that I did now is different than before. Before, I clicked "run" on the report details in the example *and only then* changed the report properties.
Now, I have changed the report properties right from the start and then clicked "run" and indeed it fails in the `/metadata/cluster` stage.

Does that help?

**Comment by ali-hamud** [comment]
yup, logs say that the token you passed is not in valid format.
Are you sure you used the /GenerateToken API as described here:
https://msdn.microsoft.com/en-us/library/mt784614.aspx

valid tokens usually start with H4

**Comment by mrgoos** [comment]
Hi @ali-hamud ,
I have generated a new token now.
I'm getting passed the `/metadata/cluster`. I see my report starting to render with the 4 different pages but now, visuals aren't being displayed.
I see lot's of messages in the log viewer like this:
```> Json Object
{
  "message": "Could not render a report visual titled Overview",
  "detailedMessage": "Can't display the visual.",
  "errorCode": "OpenConnectionError",
  "technicalDetails": {
    "requestId": "bdfb40d0-9b2a-4577-1c3f-fe268eba7efc"
  }
}
```

This request fails in the network tab:
`Request URL:https://wabi-west-europe-redirect.analysis.windows.net/powerbi/metadata/models`
`RequestId:6b92be6c-701a-e2c6-8b8e-0b7507ec3385`.

So I understand now that in order to view an example of my report in the demo I need to click "run" only after putting my report properties. If I want to change the properties I need to refresh it. I think that it should be emphasize somewhere or handled.

So what are those new errors can be invoked from?

**Comment by mrgoos** [comment]
@ali-hamud - I have found out what is the current issue - using a wrong roll.
So after using the appropriate embed code of the appropriate roll - it worked.

My feedback:

1. Please amphasize somewhere that after clicking **run**, user shouldn't be able to change the report's property. Or allow it and run all the requests from the beginning.
2. When I want to test the `Apply Custom Layout` feature, I cannot since it's hard coded to show `VisualContainer7` and `VisualContainer4`. Please allow editing this code (is this possible?) or show `VisualContainer0`, `VisualContainer1` to match all cases.

WDYT?
Thanks @ali-hamud.

**Comment by ali-hamud** [comment]
Hi @mrgoos 
Thank you for your feedback.
one thing: you can run the sample code you see in "development tools" hitting F12.
It works the same as clicking "run".

Thus, copy the sample code, change it and run in browser console.

**Comment by mrgoos** [comment]
Thanks @ali-hamud.
It works, though a bit hacky :)
Do you have plans to configure it in a better way in the future?
This hack has many flaws. For example, If I wanna switch between tiles I cannot do it (JS Error in the console).
Thanks a lot for the support.

**Comment by ali-hamud** [comment]
What do you mean by switching between tiles?
All API calls should work from the console.

**Comment by mrgoos** [comment]
If I copy-paste the code from `Apply Custom Layout` it will work only once for a page reload.
If I run it the 2nd time without reloading the page I get: 
```
Uncaught SyntaxError: Identifier 'defaultLayout' has already been declared
    at <anonymous>:1:1
```

**Comment by ali-hamud** [comment]
Make the code editable is in our backlog.
you get this error because parameter is already defined in console scope.
just remove the "let" and the "var" from the sample code, and then you can run it as much as you want.
