### ISSUE TITLE
Embed multiple visuals from page in a single report

### ISSUE THREAD

**Issue by mrgoos** [Microsoft/PowerBI-JavaScript#317]
Hi,
I need to embed multiple visuals from a page in a single report.
Let's say that I have multiple pages with multiple visuals in each page, I would like to show a report with, for example, only 2 visuals from a specific page.
There's a relation between these visuals so I want it to be kept (clicking on 1 visual should affect the 2nd visual display).
How can this be accomplished?
I've only seen examples of one visual from one page:
![image](https://user-images.githubusercontent.com/2561935/35633644-6f2e798c-06b2-11e8-8be2-71ce8f5caf3c.png)
I thought of maybe creating a different report variable for each visual but I think that by this I will lose the interaction between them, won't I?

What's the best practice for that?
Thanks.

**Comment by ali-hamud** [comment]
Use Custom-Layout feature.
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Custom-Layout

you can also try it in Live demo.
embed a report, go to interact page, and click on Apply Custom Layout sample code, which will embed two visuals from one page.

**Comment by mrgoos** [comment]
Thanks a lot @ali-hamud !
Yes, I also saw it now well documented in Custom Layout (New) in the wiki.
Closing it.
