### ISSUE TITLE
Possibility to dynamically add theme to a visual

### ISSUE THREAD

**Issue by mrgoos** [Microsoft/PowerBI-JavaScript#319]
Hi guys,
When we have attended the conference on your site you've mentioned something about being able to customize each visual's theme through the API.
Can you tell when this will be GA?
Thanks.

**Comment by ali-hamud** [comment]
Not the theme but you can control the position, size and visibility of each visual.
read about this here:
https://github.com/Microsoft/PowerBI-javascript/wiki/custom-layout

**Comment by mrgoos** [comment]
That I saw. What about the theme itself, css etc?
@ali-hamud
