### ISSUE TITLE
using updateSettings() to update customLayout does not work.

### ISSUE THREAD

**Issue by j-windsor** [Microsoft/PowerBI-JavaScript#322]
The following line has no effect on the report. This assumes the display mode is initially set to `fitToPage`.

```typescript
this.report.updateSettings({
                customLayout: {
                    displayOption: models.DisplayOption.ActualSize,
                },
            });
```

Changing other settings using `updateSettings()` does work, such as `filterPaneEnabled`.

**Comment by ali-hamud** [comment]
You should pass LayoutType: Custom.

**Comment by ali-hamud** [comment]
see https://github.com/Microsoft/PowerBI-JavaScript/wiki/Custom-Layout

**Comment by j-windsor** [comment]
Thanks!
