### ISSUE TITLE
Add type structure for ReportLevelFilters in wiki (or link to it if it's somewhere else)

### ISSUE THREAD

**Issue by acomito** [Microsoft/PowerBI-JavaScript#327]
I'm trying to track down the structure of ReportLevelFilters from [here](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Embed-Configuration-Details). Looks like we're passing in an array of objects of type ReportLevelFilters? I'm sure it's somewhere on the internet but it would be great to have it linked/shown there in the wiki.

edit: https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_powerbi_models_dist_models_d_.ireportloadconfiguration.html

**Comment by ali-hamud** [comment]
updated here:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters

Thanks.
