### ISSUE TITLE
PowerBI.com section of the Wiki - Embedding-Basics

### ISSUE THREAD

**Issue by sjkp** [Microsoft/PowerBI-JavaScript#43]
I just realized that I could change the wiki, so I took the liberty to change something that I believe was a mistake, but just wanted to let you know in case I'm mistaken. 

In the PowerBI.com section you had the exact same embed-url's as in the Power BI Embedded (Azure) section
`powerbi-embed-url="https://embedded.powerbi.com/appTokenReportEmbed"`

I believe it should have been:

`powerbi-embed-url="https://app.powerbi.com/reportEmbed"`

At least the later is working for me, while the former isn't.

**Comment by mattmazzola** [comment]
Thanks for making the change and thanks for letting us know.

Your url change is correct.  I forgot to enable the wiki edit restriction to contributors only.  I have enabled it now so future edits will have to be done through pull requests but this will protect us from people accidentally putting incorrect info on there.
