### ISSUE TITLE
updateSettings JS API is not working

### ISSUE THREAD

**Issue by wbreza** [Microsoft/PowerBI-JavaScript#44]
When calling the `updateSettings(...)` function on the report embed object - the settings are not being applied.

**Comment by wbreza** [comment]
There is currently a mismatch between the SDK and the required Power BI product code.  The `updateSettings()` command will be supported on the next product release tentativly scheduled for 8/8/2016.

**Comment by lvanderbijl** [comment]
Hello, any update on when this will be released?

**Comment by pkwiecien** [comment]
We fixed the Power BI product code. It should be deployed this Wednesday so updateSetting should start working then.

**Comment by mschulz531** [comment]
What about showFilterPane=false?

**Comment by pkwiecien** [comment]
The property name is **filerPaneEnabled**=true/false and it should work, doesn't it?
See e.g. https://microsoft.github.io/PowerBI-JavaScript/demo/filters.html

**Comment by mschulz531** [comment]
The following code does not cause the filter to be hidden:

```
    var reportConfig = { settings: { filterPaneEnabled: false } };
    var reportElement = document.getElementById('pbi-report');
    var report = powerbi.embed(reportElement, reportConfig);


```
Matt mentioned something about the Power BI product code being out of sync with this module and that a fix was needed for this, similar to updateSettings...

**Comment by mattmazzola** [comment]
The code which sets the state of the report on load does some extra work than the code which simply updates existing settings.  In other words, executing `powerbi.embed(reportElement, reportConfig)` is not the same as `report.updateSettings(settings)`. 

To be clear there was an actual bug with the former: `powerbi.embed(....)` which is being fixed.  The out of sync issue was with the direct `report.updateSettings` API.  I will try confirm if this fix is indeed in prod later today.

**Comment by mschulz531** [comment]
ok thanks, I will keep watching this thread for an update.  setFilters is working great; now I just need to hide the filterPane.

**Comment by mattmazzola** [comment]
Confirmed that the `report.updateSettings(settings)` api works in prod now.
See: https://microsoft.github.io/PowerBI-JavaScript/demo/settings.html

This enables the work around for bug #45 to hide the page navigation by setting `{ navContentPaneEnabled: false }`.

Full code would be something like this:
```
report.on('loaded', event => {
  report.updateSettings({ navContentPaneEnabled: false });
});
The bug with respecting `navContentPaneEnabled` setting on report load is still

**Comment by mattmazzola** [comment]
In attempt to fix the navContentPaneEnabled on report load, the product has new bug for navContentPaneEnabled when using updateSettings.  The call will succeed but the report will not update.  
Controlling the filterPaneEnabled still works correctly.

ETA for this fix is 10/5
