### ISSUE TITLE
navContentPaneEnabled settings not being applied during report load

### ISSUE THREAD

**Issue by wbreza** [Microsoft/PowerBI-JavaScript#45]
The `navContentPaneEnabled` is not being applied when set via the `embedConfiguration` for report embeds.

**Comment by wbreza** [comment]
We have identified a bug in the underlying Power BI product code that is causing this issue.  The product team is working on a fix and should be available by the next release tentatively scheduled for 9/8/2016.

**Comment by mattmazzola** [comment]
Just updating the ETA for those waiting on this fix.  The fix will be slightly later than original expected 9/8 date.  It should be available Wednesday (9/14).

**Comment by mattmazzola** [comment]
The fix has finally reached prod. Although the fix for this introduced new bug with updateSettings. #44
