### ISSUE TITLE
Add new event to indicate when all report visuals have finished rendering.

### ISSUE THREAD

**Issue by mattmazzola** [Microsoft/PowerBI-JavaScript#47]
There are some cases where it would be beneficial for the host application to know when the visuals have completed rendering.

Use cases:
Host application will enable printing when visuals have finished loading: #46 

Requirements:
The event should be sent after the `loaded` event.
The event should be sent after all visuals have completed the initial render.

Investigation:
It's not clear if the current implementation of visuals allows this information to be known.  Different visuals would have different render times and it may not be easy to determine what counts as an initial render.

Also, since visuals would re-render on data selection and filters being applied perhaps there is a way to make this even more generic and be emitted after visuals reach a steady state after any render instead of just initial render.

**Comment by ali-hamud** [comment]
This issue has been solved.

please update to 2.2.6 published today. you will have a "rendered" event.
it's similar to 'loaded'. we will document it in our wiki later.

basically this event is raised each time a render event completed. it could happen after a report load, or after user interaction with a report. For example: after changing current filter.

usage example:
report.on("rendered", function() { console.log("Rendered"); });
