### ISSUE TITLE
filters is invalid. Not meeting type constraint

### ISSUE THREAD

**Issue by mschulz531** [Microsoft/PowerBI-JavaScript#50]
I am getting the following error when trying to set a filter in the reportConfig object which is passed as the second argument to powerbi.embed

_filters is invalid. Not meeting type constraint_

Here is the reportConfig object:
Object {settings: Object, filters: Array[1]}

Here is the filter object (array) within the reportConfig object:
filters: Array[1]
0: BasicFilter
    operator: "In"
    schemaUrl: "http://powerbi.com/product/schema#basic"
    target: Object
        column: "SiteName"
        table: "SiteName"
        __proto__: Object
    values: Array[1]
        0: "Abbotsford_3195"
        length: 1
        __proto__: Array[0]
    __proto__: Filter
length: 1
__proto__: Array[0]

Obviously there is a problem with my filter, but I cannot determine the issue.

**Comment by mattmazzola** [comment]
Your filter is fine.  The error message of from our JSON schema validator.  I tested it using code below.

```
var basicFilter = new pbi.models.BasicFilter({ table: "SiteName", column: "SiteName" }, "In", ["Abbotsford_3195"]);
pbi.models.validateFilter(basicFilter.toJSON());
```
```
JSON.stringify(basicFilter.toJSON(), null, '  ')
"{
  "$schema": "http://powerbi.com/product/schema#basic",
  "target": {
    "table": "SiteName",
    "column": "SiteName"
  },
  "operator": "In",
  "values": [
    "Abbotsford_3195"
  ]
}"
```

Notice it says `filters is invalid. Not meeting type constraint` this means there is issue with the filters property on the load configuration object.  I suspect there is an issue with the way we are validating the object.

As a temporary work around you should try using `setFilters([filter])` after the report is loaded while I investigate further.

**Comment by mattmazzola** [comment]
Confirmed issue.  Closing and re-opening here: https://github.com/Microsoft/powerbi-models/issues/16

**Comment by mschulz531** [comment]
Thanks Matt, I will try the other approach and let you know how that goes.
