### ISSUE TITLE
Import a PBIX file to Embedded

### ISSUE THREAD

**Issue by rolandoldengarm** [Microsoft/PowerBI-JavaScript#52]
Is it possible to import a PBIX to Power BI Embedded using this JS library?
I can't seem to find it. 
What other solution would I have?

**Comment by mschulz531** [comment]
This JS library is primarily for communicating with the report once it is loaded.  There is a separate node.js library and a C# SDK that you can use to perform provisioning tasks such as creating workspaces, uploading .pbix files, and updating data sources/credentials.

https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started/

https://powerbi.microsoft.com/en-us/blog/pbie-nodejs-sdk/

**Comment by mattmazzola** [comment]
**Is it possible to import a PBIX to Power BI Embedded using this JS library?**
No. As the previous comment said, this library is for client applications to embed and communicate with the report, not for managing workspace collections or workspaces.

**What other solution would I have?**
As stated in our [wiki](https://github.com/Microsoft/PowerBI-JavaScript/wiki) there are two cli tools which help facilitate upload:
[powerbi-node-cli](https://github.com/Microsoft/PowerBI-Node)
[powerbi-csharp-cli](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app/tree/master/ProvisionSample)

Or if you prefer a different language you can generate your own http client using our swagger.json file:
https://github.com/Microsoft/PowerBI-Node/blob/master/swagger.json

For example, I believe other people have done this for Python and Java.
