### ISSUE TITLE
Embed report from Group

### ISSUE THREAD

**Issue by fredrikheden** [Microsoft/PowerBI-JavaScript#57]
It doesn't seem like it's possible to embed a report from a Group. Can you confirm that's the case? If so, when will this feature be included?

**Comment by wbreza** [comment]
Yes, you can embed a report from a group.  You first need to get the embed url for your group.

The following API will get you all reports within the specified **groupid**
`https://api.powerbi.com/v1.0/myorg/groups/{groupId}/reports`

After you have the embed URL you can then use the SDK just like any other report.

**Comment by fredrikheden** [comment]
I have tried to use the following code sample (from your wiki):
```
powerbi.accessToken = 'eyJ0e...gT4HB_IAVn2A';
var embedConfiguration = {
   type: 'report',
   id: '69321...2a459e',
   embedUrl: 'https://app.powerbi.com/reportEmbed'
};
var $reportContainer = $('#reportContainer');
var report = powerbi.embed($reportContainer.get(0), embedConfiguration);
```
It works fine for reports in "My Workspace", but whenever I try to use a report id from a report within a group it does not work.

**Comment by wbreza** [comment]
We will take another look and confirm if there is additional steps required for groups.  
@alihamud - Please take a look

**Comment by alihamud** [comment]
Please use PowerBI RestAPI to get the report embed url from group:

``
https://api.powerbi.com/v1.0/myorg/groups/{groupId}/reports
``

once you have the embed url, please use one of the following 2 ways to embed it:
first way:
```html
<html>
<head>
<script src="https://code.jquery.com/jquery-3.1.1.js" integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA=" crossorigin="anonymous"></script>
</head>
<body>
	<div id="reportContainer"></div>
	<script src="powerbi.js"></script>
	<script>
		var embedConfiguration = {
			type: 'report',
			accessToken: 'eyJ0eXAiOiJKV1Q..RR3',
			embedUrl: 'https://msit.powerbi.com/reportEmbed?reportId=968df801-3378-46c1-a48e-adbff867bc68&groupId=71127d49-49a7-4b9d-811d-0df541beab9b'
		};
		var $reportContainer = $('#reportContainer');
		var report = powerbi.embed($reportContainer.get(0), embedConfiguration);

	</script>
</body>
</html>
```

second way:
```html
<html>
<body>		
	<div
		id="pbiEmbedDiv"
		powerbi-type="report"
		powerbi-embed-url="https://msit.powerbi.com/reportEmbed?reportId=968df801-3378-46c1-a48e-adbff867bc68&groupId=71127d49-49a7-4b9d-811d-0df541beab9b"></div>
		
	<script src="powerbi.js"></script>
	<script>
		// SAAS Embed - used in PowerBI.com service. access token is per user. with this token, user can see all his reports.
		powerbi.accessToken = 'eyJ0eXAiOiJ...qdA';
	</script>
	<script>
		powerbi.enableAutoEmbed();
	</script>
</body>
</html>

```

**Comment by fredrikheden** [comment]
Thank's, it works now. I had to change "msit.powerbi.com" to "app.powerbi.com" though.

**Comment by alihamud** [comment]
yeah sure.
glad I helped.

**Comment by qwe6895** [comment]
Hi, just one thing,

how are we getting value for access token ?
Kindly help me with this

**Comment by vaibhav-goyal** [comment]
@alihamud 
I am using the first method you suggested but I am getting following errors in browser console
```
_GET https://wabi-south-east-asia-redirect.analysis.windows.net/powerbi/metadata/models 403 (Forbidden)
GET https://wabi-south-east-asia-redirect.analysis.windows.net/metadata/cluster 401 (Unauthorized)_
```

Finally the browser displays

```
This content is not available.
Learn more about Power BI.
```

**Note : Sometimes the report works but suddenly after an hour i start seeing the issue**
