### ISSUE TITLE
How to get powerbi-access-token

### ISSUE THREAD

**Issue by jaivirmalik** [Microsoft/PowerBI-JavaScript#58]
I not able to understand, how to get powerbi-access-token using access key or any other way.

**Comment by jaivirmalik** [comment]
Done

**Comment by joanteixi** [comment]
Sorry to open this again... did you get the access token with adal or some other library? Thanks

**Comment by ali-hamud** [comment]
Adal is good.
please see this E2E sample:
https://github.com/Microsoft/PowerBI-Developer-Samples
