### ISSUE TITLE
Where do you get the token from?

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/PowerBI-JavaScript#59]
In the Azure Embedded demo, you have an API that generates a unique token that is used to get the report. If you use the access token from the Azure Portal, it does not work. Is there a way to get the token without needing an additional API to generate?

**Comment by alihamud** [comment]
can you please explain that more?
what API you are talking about? can you copy the code from the sample?

**Comment by isaac2004** [comment]
I figured it out myself.
