### ISSUE TITLE
Embed error 500 for some users

### ISSUE THREAD

**Issue by fredrikheden** [Microsoft/PowerBI-JavaScript#60]
When embedding a Power BI report from a group in a web capplication a lot of our users get a "500 internal server error" thrown from "/metadata/cluster" and no report is shown. This does not occur when embedding dashboard tiles, only for reports. It does not occur for all users, but for many of them. All users have the same security settings and can access the report fine from directly powerbi.com. Any idea of what might be the issue?

**Comment by alihamud** [comment]
We are looking into it.  I will update later.
Thanks for opening this issue.

**Comment by fredrikheden** [comment]
Good to hear. Let me know if you want any fiddler traces or other information related to the issue.

**Comment by alihamud** [comment]
Hi fredrikheden,
we've fixed the problem, can you please verify if the problem is still there?
if the problem is not solved, please send me fiddler traces.
Thank you.

**Comment by fredrikheden** [comment]
Hi, 
This is not the same error as the "401 Unauthorized" error all of us got last week. This error is still there and is not resolved. Some users cannot look at embedded reports - they get a 500 error (as stated above).
Where can I send the fiddler trace?

**Comment by alihamud** [comment]
can you attach them here in a comment?

**Comment by fredrikheden** [comment]
I would prefer not sharing them publicly. Can I mail them to you?

**Comment by alihamud** [comment]
Sorry for the late response.
please send to pbiei@microsoft.com
please put a link to the issue inside the email. thank you for collaboration.

**Comment by alihamud** [comment]
Hi Fredrik,
We found the bug, we are working on the fix.
I will notify when it's done.
Thank you.

**Comment by fredrikheden** [comment]
Ok, so you don't need the Fiddler-trace anymore I guess. Can you give me any time indication on when the bug till be corrected?

**Comment by nthvu90** [comment]
Hi alihamud. Fredrik 's  problem has been solved yet? I also encountered this error, i try fixing many ways but i can not resolve this issue

**Comment by ali-hamud** [comment]
Hi, this problem is solved. please re-validate.
please re-open if it is not solved for you.

**Comment by andrecarlucci** [comment]
Hi guys,
I'm having the same error: "This content is not available".
In my case, only 500s on  https://wabi-south-central-us-redirect.analysis.windows.net/metadata/cluster

The weird thing is that it was working fine this morning, but now it fails with this message every time I try.

To reproduce, I downloaded the power-bi-embedded-integrate-report-into-web-app repository, only changed the web.config with my keys and I get the error every time.

Any thoughts?

**Comment by cristianbatist** [comment]
I entered the error as follows:

1- When I enter the embedded report with the user Test and give the error 500.

2- Enter the https://powerbi.microsoft.com and access the report through the portal.

3- I give the refresh on embedded and it works.

Is there any relationship between you being able to enter embedded only if you have already entered the report at https://powerbi.microsoft.com.

Here's the tip to help with the solution.

**Comment by andrecarlucci** [comment]
Just to follow up, I did nothing and the next day it was working.
Is this common? Maybe some problem with the powerbi servers?

**Comment by cristianbatist** [comment]
This problem happened to me today and I noticed this behavior.

However it has happened before and came back from nowhere, I believe embedded is not yet very stable.

Debugging the code I saw that this problem occurs in the validation of the token.

**Comment by cruise-insights** [comment]
@andrecarlucci @cristianbatist @ali-hamud 

We did face the issue, that too in production environment !

![image](https://cloud.githubusercontent.com/assets/7963522/22524304/b47ad53c-e8e8-11e6-9c27-e3f3eaec948a.png)


The 500 internal server error , while using Power BI embedded typically occurs **when 2 users mapped to the same workspace try accessing the report at same time.**

**Reason ->** In such scenario 2 embed configurations( jwt access token ) need to be generated for same report at same time, out of which only one can be alive.
(This is what I figured out).

Hope that helps!!

**Comment by ArinaHantsis** [comment]
@cruise-insights, could you please provide the session id for the failing request from the network capture utility in the browser or through Fiddler? If you expand the request you should find it ....
With the very limited information I have from your screenshot I was able to see that you were passing a null token that cannot be parsed to JWT valid token.

Regarding multiple users assumption, I don't think there is a problem to have multiple users view the same report from different browsers, please use our live demo sample for an example: https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html

**Comment by ArinaHantsis** [comment]
@cristianbatist - the issue you're described seems to be related to a problem we identified when users try to access PowerBI content from within a group while they didn't logged-in to https://powerbi.microsoft.com since they were added to this group .... We fixed this issue and it's expected to reach production next week.
Please provide some troubleshooting information in case you encounter this again or any other issue.

**Comment by ArinaHantsis** [comment]
@cristianbatist - the issue you described seems to be related to a problem we identified when users try to access PowerBI content from within a group while they didn't logged-in to https://powerbi.microsoft.com since they were added to this group .... We fixed this issue and it's expected to reach production next week.
Please provide some troubleshooting information in case you encounter this again or any other issue.

**Comment by cristianbatist** [comment]
@ArinaHantsis 
That's exactly the problem I have.
I will be waiting for the production solution and notice when it is ok.
Can you please let us know when this fix is in production for me to do the tests.
Thank you very much.

**Comment by cruise-insights** [comment]
@ArinaHantsis , I have a server setup for token formation (Power BI Embedded) that returns encoded jwt.
So our users dont have to login through Power BI.

The internal server error occurs when multiple users are mapped to same workspace in a Azure workspace collection. And try to access same report at same time.

Solution: - Dont map multiple users to same workspace.

Regards

**Comment by ali-hamud** [comment]
@cristianbatist it should work.
you can give multiple users tokens to the same report.
take for example this live sample, and try to embed a sample report from different machines the same time, it works:
https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html

if it doesn't work for you, it could be a bug or a special case which needs more investigating.

**Comment by cruise-insights** [comment]
@ali-hamud , 
We had issued multiple access token dynamically through a node service, at almost same instant, for direct query  reports.
But upon calling powerbi.embed() --> one instance showed report , other showed internal server error(as per pic) .

**Comment by ali-hamud** [comment]
what parameters you give powerbi.embed in both cases?
can you give us: RequestId, it should appear in request Header.

**Comment by cruise-insights** [comment]
@ali-hamud 
embedConfiguration= ajax{ /GET @ my service} 

powerbi.embed(element,embedConfiguration);
The snapshot was shared by one of our Clients in production .
To give request id, I will have to replicate the situation, as now we are not assigning 2 workspaces to one client. 
Post this configuration , we arent facing issues.
