### ISSUE TITLE
Promise is not defined powerbi.js

### ISSUE THREAD

**Issue by alpha2aplicativos** [Microsoft/PowerBI-JavaScript#61]
Hi i am embedding the powerbi in a winforms and use the web browser to view a Web site that contains the built-in reports, the problem is that the web browser launches that promises is not defined in powerbi.js. The iframe usually works but I developed a script to filter the report by the url and other controls do not work because it is always released this error: promises is not recognized in powerbi.js. If you can help me I will be very grateful

**Comment by pkwiecien** [comment]
Looks like a similar issue to this one: https://github.com/Microsoft/PowerBI-JavaScript/issues/54
Can you try suggested solution there? Let us know if it worked.

**Comment by alpha2aplicativos** [comment]
I just test and it worked like a glove. Thank you for the help.
I just added <script src="https://npmcdn.com/es6-promise@3.2.1"></script>
and works fine! Thank you soooo much.
