### ISSUE TITLE
Is there minimum size limitation of a report?

### ISSUE THREAD

**Issue by petercoin** [Microsoft/PowerBI-JavaScript#62]
I have a report contains only one visualization with height for 180 pixels and width for 360 pixels and I also modified the report size to fit the visualization.

However, after I embed it into my web, it only shows a part of the visualization if I set the height for 180 pixels and width for 360 pixels with CSS style.
![p1](https://cloud.githubusercontent.com/assets/12906762/18979171/2ec6fffa-86fb-11e6-9d7e-ebd88b0f5697.PNG)

If I change the height to 360 pixels, the visualization shows with blank spaces on top and bottom.
![p2](https://cloud.githubusercontent.com/assets/12906762/18979170/2ec6f460-86fb-11e6-9982-edd050fbbfde.PNG)

My question is that is there any size limitation of a report and how can I remove the blank so that I can show only the visualization on my web?

**Comment by petercoin** [comment]
Can anyone give me some comments?
I have to know the root cause...

**Comment by ali-hamud** [comment]
How did you modified the report size?

**Comment by petercoin** [comment]
Hi Ali,
I use Power BI Desktop to create the report first and set the size to 360(W)*180(H).
And then embed the report with html attribute and set CSS style to 360(W)*180(H).
With this condition, the result is the same as first image.
Below is my cshtml source code:
```cshtml
<td style="width:360px;height:180px;"
            powerbi-type="report"
            powerbi-access-token=@Model.Deals.AccessToken
            powerbi-report-id=@Model.Deals.Report.Id
            powerbi-embed-url=@Model.Deals.Report.EmbedUrl
            powerbi-settings-filter-pane-enabled="false"
            powerbi-settings-nav-content-pane-enabled="false"></td>
```

**Comment by ali-hamud** [comment]
sorry, I am not getting to try this. but I will.
I am not aware of any limitations, but I should try it.

**Comment by ali-hamud** [comment]
Sorry for the long time.
There is a min height. it's 320 I think.

**Comment by petercoin** [comment]
Hi Ali,
Thank you for your greatly support.
