### ISSUE TITLE
Failed to Load Settings 

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/PowerBI-JavaScript#63]
I followed the demo example exactly and am getting this error when I go to embed a report. Here is the JS Code I have

` // Scenario 1: Static Embed
                    var staticReportUrl = '/api/Admin/GetReportToken?reportId=021d58d9-48b3-4362-976b-23a7181c0aa9';
                    var $staticReportContainer = $('#reportContainer');

                    fetch(staticReportUrl)
                      .then(function (response) {
                          if (response.ok) {
                              return response.json()
                                .then(function (embedConfig) {
                                    vm.staticReport = powerbi.embed($staticReportContainer.get(0), embedConfig);
                                });
                          }
                          else {
                              return response.json()
                                .then(function (error) {
                                    throw new Error(error);
                                });
                          }
                      });`

I get the error message, but the report still renders on the page. The request that is failing is this one

Request URL:https://wabi-west-us-redirect.analysis.windows.net/powerbi/metadata/userSettings
Request Method:GET
Status Code:401 Unauthorized

It seems it makes a request as an HttpOptions, than as a HTTPGet, the Get failing. Here is the successful call with options

Request URL:https://wabi-west-us-redirect.analysis.windows.net/powerbi/metadata/userSettings
Request Method:OPTIONS
Status Code:200 OK

This stopped working all of a sudden. Is there an additional parameter that I need to be sending to the request?

**Comment by davidyang99** [comment]
Got the same issue in the demo meeting. Really embarrassed...

**Comment by davidyang99** [comment]
Here is what I got when I showed the demo from http://azure-samples.github.io/powerbi-angular-client/#/scenario5

Something went wrong.
Failed to load settings
Please try again later or contact support. If you contact support, please provide these details.
Activity ID973387c3-fe41-4b99-abdf-fac3e84003f6
Request IDd05170f8-6c70-b95e-3691-7940ed114a31
Correlation ID7b8de6bb-6f3d-58d5-f4c2-a5e8c9b34386
Status code401
TimeFri Sep 30 2016 12:33:27 GMT-0400 (Eastern Daylight Time)
Version13.0.1700.320
Cluster URIhttps://WABI-CANADA-CENTRAL-redirect.analysis.windows.net

**Comment by alihamud** [comment]
Hi david,
please check if the problem still there. we solved it.
Thank you,
Ali Hamud

**Comment by isaac2004** [comment]
This is now fixed. Tested today

**Comment by diptesh912** [comment]
Request URL:https://df-msit-scus-redirect.analysis.windows.net/metadata/cluster
Request Method:GET
Status Code:403 Forbidden
Remote Address:40.84.158.255:443

**Comment by RahulSolanki1487** [comment]
for me it's giving same error:
wabi-us-north-central-redirect.analysis.windows.net/metadata/cluster : Failed to load resource: the server responded with a status of 403 (Forbidden)
i'm using angular2 with power bi javascript API to embed report. can anyone please help me with proper solution.

**Comment by ali-hamud** [comment]
are you sure you are passing correct tokenType in load settings?
if you are using EmbedToken - use models.TokenType.Embed
if you are using Bearer token - use models.TokenType.Aad
