### ISSUE TITLE
Dynamically add filter to Date column

### ISSUE THREAD

**Issue by jetdotnet** [Microsoft/PowerBI-JavaScript#66]
How do I create a filter against a date type field? Ideally I would like to create an advanced filter to capture dates within a range but I have not been able to apply any filter to a date field.

For example, I have tried using a basic filter to select just a single date.
```javascript
           const filter = {
                target: {
                    table: "DimDate",
                    column: "Date"
                },
                operator: "In",
                values: ["2016-09-01"]
            };
```

This adds the filter to the report but the filter in the report has a yellow alert icon next to it and when I hover over it I get "This filter can't be used since the corresponding field is invalid."

If I try and create an advanced filter such as
```javascript
            const filter = {
                target: {
                    column: "Date",
                    table: "DimDate"
                },
                logicalOperator: "And",
                conditions: [
                    {
                        operator: "IsOnOrAfter",
                        value: "2016-09-19"
                    }
                ]
            };
```
I get an "Invalid filter definition" message in my console.

What is the correct way to do this?

**Comment by pkwiecien** [comment]
See the following section in wiki on expected date format: https://github.com/Microsoft/powerbi-models/blob/dev/README.md#date-formatting
