### ISSUE TITLE
Data refresh not showing up in embedded report

### ISSUE THREAD

**Issue by isaac2004** [Microsoft/PowerBI-JavaScript#67]
The report that is embedded on my page does not match the report that is out on the Power BI portal. The embedded report is powered by a PowerBI workspace collection that I created by uploading a pbix file. It looks like the embedded report is using some cached version from weeks ago. Is there an additional step that needs to be done to sync the embedded report with power bi?

**Comment by alihamud** [comment]
How do you see a report from a WorkspaceCollection in Power BI portal?
have you uploaded the file twice?

**Comment by isaac2004** [comment]
I published through Power BI desktop. Is there a way to sync the 2 locations together?

**Comment by ali-hamud** [comment]
I think you uploaded the file twice,  one using portal, and one using import api, or powerbi-cli.
In that case there is no way to connect them together. 

Can you explain what are the steps you did?

**Comment by isaac2004** [comment]
I uploaded initially to create the dashboard. I then used the console app to create the workspace. Is there a way to connect an embedded power bi to an existing data source?





On Thu, Oct 27, 2016 at 5:29 PM -0400, "ali-hamud" <notifications@github.com> wrote:












I think you uploaded the file twice,  one using portal, and one using import api, or powerbi-cli.

In that case there is no way to connect them together. 



Can you explain what are the steps you did?

**Comment by ali-hamud** [comment]
What is your data source?

I think you are looking into a way to connect the two reports (embedded one and portal one) to the same data source,  and you will refresh the data source one time for both reports. 
I think such functionality is not supported yet.
I am re-checking.

**Comment by isaac2004** [comment]
It is Azure Sql. 





On Thu, Oct 27, 2016 at 5:42 PM -0400, "ali-hamud" <notifications@github.com> wrote:












What is your data source?



I think you are looking into a way to connect the two reports (embedded one and portal one) to the same data source,  and you will refresh the data source one time for both reports. 

I think such functionality is not supported yet.

I am re-checking.

**Comment by ali-hamud** [comment]
I an suggesting to use DirectQuery data source.
https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started/#create-power-bi-datasets-and-reports-to-embed-into-an-app


Point the two reports to the same azure sql.
In portal use refresh functionality. 
In embedded, you ahould use refresh method to refresh a report (still in beta, dev branch)
https://github.com/Microsoft/PowerBI-JavaScript/blob/dev/src/report.ts

**Comment by isaac2004** [comment]
Can you provide a sample pbix file that uses direct query?





On Thu, Oct 27, 2016 at 6:25 PM -0400, "ali-hamud" <notifications@github.com> wrote:












I an suggesting to use DirectQuery data source.

https://azure.microsoft.com/en-us/documentation/articles/power-bi-embedded-get-started/#create-power-bi-datasets-and-reports-to-embed-into-an-app



Point the two reports to the same azure sql.

In portal use refresh functionality. 

In embedded, you ahould use refresh method to refresh a report (still in beta, dev branch)

https://github.com/Microsoft/PowerBI-JavaScript/blob/dev/src/report.ts

**Comment by isaac2004** [comment]
Any update on my request?

**Comment by ali-hamud** [comment]
We are working on defining the billing for refresh. we may publish the refresh to latest this week or next week.
Thanks for your understanding.

**Comment by isaac2004** [comment]
Great, please comment in this thread when pushed

**Comment by isaac2004** [comment]
@ali-hamud what is the status of this enhancement?

**Comment by ali-hamud** [comment]
unfortunately, we didn't look into this feature yet. we have bunch of requests.

**Comment by isaac2004** [comment]
@ali-hamud do you know when it will be looked at? Also there is no refresh method on embedded at the location you provided.

**Comment by petercoin** [comment]
Hi Issac,
The way I used to create a DirectQuery Power BI report is as below:
1. Use Power BI Desktop to create a report and data source is from Azure SQL.
Remember to select **DirectQuery** instead of **Import**.
2. Download a [sample project](https://github.com/Azure-Samples/power-bi-embedded-integrate-report-into-web-app) from Github.
3. You can find a application which is named ProvisionSample.exe under ProvisionSample\bin\Debug.
4. Use the application to create workspace collection in PowerBI workspace on Azure.
![image](https://cloud.githubusercontent.com/assets/12906762/21179205/04440f52-c22e-11e6-8fb7-c5ec2b05097c.png)

5. You will find a collection is created under PowerBI workspace from Azure portal. 
![image](https://cloud.githubusercontent.com/assets/12906762/21179185/ea1cddd4-c22d-11e6-8b3f-8f809e0b0d90.png)

6. Use the application to import pbix file into workspace collection.
7. Use the application to update connection string info because the sensitive data will be removed from pbix file.
※You may run into a problem that connection string cannot be updated. The solution is to skip entering connection string and the update process will be successful.

You also can refer to this [website](https://docs.microsoft.com/en-us/azure/power-bi-embedded/power-bi-embedded-get-started-sample) to know more information.

**Comment by fume** [comment]
Hi @ali-hamud, still no news about the refresh function? And as @isaac2004 said, there is no refresh function in the dev branch! What are we missing?

Thanks, regards

**Comment by ali-hamud** [comment]
we will give this a priority.
let me update in two days.

Thank you for pulling this up again.

**Comment by fume** [comment]
Hi @ali-hamud , sorry for bowering you. Any update? :)

Regards, FM

**Comment by ali-hamud** [comment]
In Code Review.
[https://github.com/Microsoft/PowerBI-JavaScript/pull/150](https://github.com/Microsoft/PowerBI-JavaScript/pull/150)

Hope we can merge it soon.

**Comment by ali-hamud** [comment]
refresh is available now in version 2.3.0

**Comment by ali-hamud** [comment]
usage: report.refresh()

**Comment by ajiljins** [comment]
Thanks a ton..!. I was using the dev branch code to test this. Hope this will be now part of NuGets package version 2.3.0 too...

**Comment by ali-hamud** [comment]
It's part of the Nuget as well.

**Comment by ltbarraza** [comment]
Hello Ali, I hope you are well.
I would like to know if the reports that are imported to the workspace collection that are created in the Microsoft Azure Service (Embedded Power BI) can somehow be updated or kept updated after they are embedded in an application or are they static?

I appreciate in advance the information you can provide.

**Comment by ltbarraza** [comment]
Hello @ali-hamud, I hope you are well.

I would like to know if the reports that are imported to the workspace collection that are created in the Microsoft Azure Service (Embedded Power BI) can somehow be updated or kept updated after they are embedded in an application or are they static?

I appreciate in advance the information you can provide.

**Comment by isaac2004** [comment]
@ltbarraza you need to have Direct Query
