### ISSUE TITLE
getFilters results not working (including in demo applications )

### ISSUE THREAD

**Issue by rquintino** [Microsoft/PowerBI-JavaScript#68]
is there some pending issue with getFilters, we can't get it to return the current filters (any level), 
 same is valid/visible in the sample applications, Applied filters refresh filters doesn't update as it should .

callback never gets executed, no error, get is pushed to /report/filters but no results after that?
(same for angular client demo)

thx!

   filterable.getFilters()
        .then(function (filters) {
          console.log(filterable.displayName, filters);
          $element.empty();
          filters
            .map(generateFilterElement)
            .forEach(function ($filter) {
              $element.append($filter);
            });
        });

**Comment by alihamud** [comment]
Bug verified. getfilters doesn't work.

**Comment by bz3361** [comment]
what's the timeline to have this bug fixed?
Is setfilters method working?

**Comment by shand-obs** [comment]
I tracked this down to an error in the ReportEmbedFilterService class, getFilters method, where in success situations, the method does not resolve the promise it is returning. I'm guessing this baby is originally written in TypeScript, so it isn't going to map up exactly with their code, but should be easy to find. Here's the erroneous code:

`                    ReportEmbedFilterService.prototype.getFilters = function (level) {
                        var _this = this;
                        var getFiltersDeferred = this.promiseFactory.defer();
                        var filterWithScope = this.getFilterContainerWithScope(level);
                        if (!filterWithScope || !filterWithScope.contract) {
                            getFiltersDeferred.reject(reportembed.HostCommunicationHelper.buildSetFilterFailedMessage());
                        }
                        else {
                            **this.getConceptualSchema().then(function (conceptualSchema) {
                                return _this.jsonFilterParser.tryGetFilters(filterWithScope.contract, conceptualSchema);**
                            }, function (error) {
                                getFiltersDeferred.reject({ message: ReportEmbedConstants.ErrorMessages.filtersSerializationError });
                            });
                        }
                        return getFiltersDeferred.promise;
                    };`

I can think of three different ways to solve this with my limited knowledge of what is going on. I'd probably do it something like this:

`                            this.getConceptualSchema().then(function (conceptualSchema) {
                                return _this.jsonFilterParser.tryGetFilters(filterWithScope.contract, conceptualSchema).then(function(filters) { getFiltersDeferred.resolve(filters); });`

Just in case it helps speed up the resolution of this bug. Sadly, this can't be fixed in the client API. It's stuff in the iframe it makes. The good news is, no download should be necessary for us. They just need to fix it on the powerbi web server.

**Comment by szahn** [comment]
+1 Please fix

**Comment by fulky** [comment]
Yes please fix.   This is key to using Power BI Embedded in a custom application

**Comment by ali-hamud** [comment]
.
     .

**Comment by ali-hamud** [comment]
Sorry for the late response. Fix coded and will be submitted soon.

**Comment by ali-hamud** [comment]
ETA for fix is next Monday 7/11

**Comment by github4me** [comment]
hi there, when will the new deployment take place, roughly? thanks

**Comment by ali-hamud** [comment]
Issue is fixed. Please verify.

**Comment by red42** [comment]
Installed 2.2.1 from npm today. I now get a return, but it's an empty array. I'm setting the filters on the embedded pane and running this in the console:

`report.getFilters().then( function(filters) { console.log(filters) })`

**Comment by ali-hamud** [comment]
what filters do you have in filter pane?

**Comment by red42** [comment]
![filters](https://cloud.githubusercontent.com/assets/4925492/20346459/38cc506a-abe3-11e6-83a8-06ad4d182a94.png)

Here's what I have. The data is just a list of different products and cities where sales occurred. I have selected a couple of cities in the filter pane, and ran getFilters on the report, which can be seen on the browser console to the right.

**Comment by ali-hamud** [comment]
We are  not supporting Visual level filters yet.
please try report level filter or page level filter.

**Comment by red42** [comment]
I see, it works correctly with report level filters. Thank you!
