### ISSUE TITLE
pop up javascript error when report is loading in IE11

### ISSUE THREAD

**Issue by davidyang99** [Microsoft/PowerBI-JavaScript#69]
Line: 3499
Error: 'Promise' is undefined

**Comment by shand-obs** [comment]
This can be solved by including a ES6 Promise poly-fill in your <head> element, such as:

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/es6-promise/4.0.5/es6-promise.auto.min.js"></script>

**Comment by davidyang99** [comment]
Thanks!

**Comment by mrgoos** [comment]
Hi, Do we need this on the new releases as well?
If so, do you plan to fix it in the future?
Thanks.
@ali-hamud
