### ISSUE TITLE
The "filtersApplied" event on reports does not work.

### ISSUE THREAD

**Issue by shand-obs** [Microsoft/PowerBI-JavaScript#70]
The following example wires up the `filtersApplied` event, but it never fires. Note that `"filtersApplied"` is included in the array returned by `powerbi.embeds[0].allowedEvents`.

```
$(function() {
    powerbi.init();
    powerbi.embeds[0].on("filtersApplied", function() {
        console.log("filtersApplied");
    });
});
```

This example assumes there is a declarative powerbi report in the html already.

The `filtersApplied` event also never fires with a manually wired event handler via the developer console.

**Comment by szahn** [comment]
+1

**Comment by ali-hamud** [comment]
filtersApplied is not supported yet.

**Comment by shand-obs** [comment]
@ali-hamud [This page](https://github.com/Microsoft/PowerBI-JavaScript/wiki/Handling-Events) disagrees with you.

**Comment by ali-hamud** [comment]
@shand-obs The documentation in the page you sent is not correct.
filtersApplied is not supported yet, I will update the documentation. Thank you.

**Comment by shand-obs** [comment]
Can you speak to when we can expect this? It's a pretty big deal for us.

**Comment by noanu** [comment]
@shand-obs this fix is on our backlog. I can't give you an ETA now, but will update here when I have more information.

thanks.

**Comment by ali-hamud** [comment]
As I said in issue #8:
[https://github.com/Microsoft/PowerBI-JavaScript/issues/8](https://github.com/Microsoft/PowerBI-JavaScript/issues/8)

we add "**Rendered**" event.
you may listen on this event to know if something changed.

If user changes the current filter, your app will receive "rendered" event.
Then, you can call the getFilters to receive the new filters.

please try it on **2.2.6** and tell me if it helps.

I am closing this issue. please re-open if this solution is not good for you.

Thank you,
Ali Hamud

**Comment by jfolds** [comment]
I am running into this issue still, and the "rendered" event mentioned does fire, but user selected filters do not get returned. This is the same behavior as seen on the demo app here: https://microsoft.github.io/PowerBI-JavaScript/demo/code-demo/index.html

`report.getFilters()` only seems to return filters that have been set with `report.setFilters` and not the user generated filters in the UI.

Thanks for any help in advance.

**Comment by rustagirohit** [comment]
Hi in my app , report rendered event was working pretty fine , but off sudden today it has stopped firing.
My code implementations associated with this rendered event are not working now. Please let me know incase there is something i can work around on to get this fixed.

**Comment by stevenswinbank** [comment]
This appliedFilters event would be really nice - when are you looking to release it? Without a consistent view of what filters are applied to a report the JavaScript API is pretty useless for implementing a better filter user experience.

**Comment by ali-hamud** [comment]
Hi,
please see previous comments about the rendered event.
you may listen on this event to know if something changed.
If user changes the current filter, your app will receive "rendered" event.
Then, you can call the getFilters to receive the new filters.

code example:
report.on("rendered", function(event) {
    report.getFilters().then(filters => {
      ... do something
   }
});

**Comment by stevenswinbank** [comment]
Yep I saw that. However, the this does not contain the 'include' or 'exclude' filters that the user may choose on a particular visual. The getVisuals method on the page object is not yet implemented either, which was where I was going to check for this. (I've been following the information model here: https://github.com/Microsoft/PowerBI-JavaScript/wiki/Understanding-the-object-hierarchy, but this seems to be the 'to-be' state, not what is currently available).

**Comment by noanu** [comment]
Hi,

We are working to enable both getVisuals and return filters on visuals as well (including include/exclude).
I hope we can update on an ETA soon.
