### ISSUE TITLE
Embed powerBI file to SharePoint Online

### ISSUE THREAD

**Issue by qwe6895** [Microsoft/PowerBI-JavaScript#71]
I am trying to embed power BI report to Sharepoint online using below Code:
But i am not aware of retrieving the access token value using Javascript.
Can somebody help me with this ?
![image](https://cloud.githubusercontent.com/assets/22743052/19343554/47ca09f8-9154-11e6-91a6-d5aea50f6f90.png)

**Comment by ali-hamud** [comment]
Hi,
what is that report that you want to embed? is it a report that you can see in powerbi portal? or a report uploaded to Azure?
if it's in Azure, you need to build embed token from AppKey (defined for workspace collection).
if it's PowerBI Extension, you need the user to sign-in, accept that you will access his datasets and reports and ..., and then you will have access token.

the auth is different in both scenarios.
please look on the sign-in button in these samples for example:
https://github.com/Microsoft/PowerBI-CSharp/tree/master/samples/webforms

**Comment by ali-hamud** [comment]
I am closing the issue.
if you need more help please re-open.

Here you can find more information.
**To use the PowerBI-JavaScript sdk you need to do the following:**
**Prerequisites**

A workspace in Azure PowerBI Embedded Service.
PowerBI Report imported to your workspace.

**Flow**

Once you have a report imported to PowerBI Workspace, you are ready to Embed it.
To Embed a report you need to get an Embed-Token. You can create this token in multiple ways:
Using PowerBI-Cli tool.
In .Net Code using Microsoft.PowerBI.Core package.
In NodeJS code using powerbi-api package.
