### ISSUE TITLE
setFilters(...) does not appear properly in the Filter panel.

### ISSUE THREAD

**Issue by shand-obs** [Microsoft/PowerBI-JavaScript#73]
When we use the setFilters(...) method on a report with a basic filter, the filter appears in the Filter panel as (All). This is clearly incorrect.

Example:

```
{
    $schema: "http://powerbi.com/product/schema#basic",
    target: {
        table: "Segments",
        column: "id"
    },
    operator: "In",
    values: [937]
}
```

(937 is valid id in this data)

appears as:

![image](https://cloud.githubusercontent.com/assets/21341273/19442801/dcce3574-9447-11e6-8c58-328c69cff1df.png)

**Comment by ali-hamud** [comment]
Do you have other IDs except of 937?
Thank you for your valuable issues.

**Comment by shand-obs** [comment]
That was just an example. The problem occurs with any ID in the given dataset.

**Comment by ali-hamud** [comment]
I will verify. thanks again

**Comment by ali-hamud** [comment]
I succeeded to repro the bug. I will update once we have a solution. thanks.
