### ISSUE TITLE
Cannot remove filters

### ISSUE THREAD

**Issue by szahn** [Microsoft/PowerBI-JavaScript#74]
No effective way to remove report, page and visual filters. Calling either `removeFilters` on a report or page instance does not actually remove all filters.

```
const page= this.report.page(pageName);
this.report.removeFilters();
page.removeFilters();
```

**Comment by ali-hamud** [comment]
Please pay attention that remove filters return a promise. You should use then method to assign success and error handlers.
Changing and removing filters could take a lot of time

**Comment by ali-hamud** [comment]
can you please give an example of why this doesn't work for you? data example and example of applied filter that you want to reset?
I tried the reset-filter and it works.
