### ISSUE TITLE
Uncaught TypeError: page.getVisuals is not a function(…)

### ISSUE THREAD

**Issue by szahn** [Microsoft/PowerBI-JavaScript#75]
According to the object model (https://github.com/Microsoft/PowerBI-JavaScript/wiki/Understanding-the-object-hierarchy), report and pages visuals should be accessed by calling `getVisuals()` and `getVisual()` on the page instance. But neither of these methods exist. How can filters be retrieved, set and listened to on a visual level?

**Comment by shand-obs** [comment]
We need this feature too. Please fix.

**Comment by ali-hamud** [comment]
We aware of the importance of these functionalities. we will look into them.

**Comment by DayKirby** [comment]
When I use getVisuals() on a page, a promise is returned but it doesn't seem to ever get fulfilled by either then or catch. I don't get an error. The page I'm working seems to be fine, as I can use removeFilters() with it and my page-level filters are removed.

**Comment by ali-hamud** [comment]
We don't have getVisuals method. How did you call it?
We don't have support to get visuals yet.

**Comment by DayKirby** [comment]
See below. Note that getVisuals() is defined here:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Understanding-the-object-hierarchy

Note that I really do need access to the visuals so I can clear the visual-level filters / data selections.
(I also need to be able to set data selection with javascript but I don't see that in the api yet)

// vm.report is a power bi report
vm.report.getPages().then(function (pages) {

     var firstPage = pages[0];
     firstPage.removeFilters();   // this call works, filters are removed from first page

     firstPage.getVisuals().then(function (visuals) { // this does not cause error
          console.log(visuals); // this line is not reached
     }).catch(function (err) {
          console.log(err); // this line is not reached either
     });

     // If, instead, I use:
     // var prom = firstPage.getVisuals();
     // I get a promise object returned

});

**Comment by ali-hamud** [comment]
getVisuals() or anything related to visuals is not supported yet.
I will update object hierarchy.

we want to support this, but I have no ETA.

**Comment by franmer** [comment]
Hi Ali, Do you have any news about supporting these Visuals functions? Regards

**Comment by ali-hamud** [comment]
Hi @franmer,
there are two options to support this: Rest Api or JavaScript Api.
can you please describe a use case or scenario of how will you use it?
and what visual properties you will need to be returned?

**Comment by franmer** [comment]
We need to capture a slicer selection (this can be done with the DataSelected event) and, when user navigates to another page, carry the selection to this page in which the same slicer exists. This would be like replicating a global slicer feature which PBI currently lacks. Report or page filters set/get functions don't fit our neccesities, as it filters the entire page and we need the slicer to have available all the options (after carrying the previous page selections).

**Comment by franmer** [comment]
Hi Ali, In case it wasn't clear, I am using the Javascript API. 
Looking forward to find a solution on this as client needs this functionality.

Thanks!

**Comment by marcindabrowski** [comment]
Hi Ali.  I am also using the Javascript API, and need getVisuals() method on Page object.
I also need getFilters and setFilters method on visuals - especially on built-in slicer visual.
It will be also great if I could read all slicer values.

Is there a way to do this now, or I should wait for adding this option to JavaScript library?

**Comment by marcindabrowski** [comment]
I've looked into the code and I think that it will be easy to implement this.
Could you tell me what URLs are needed? Are those correct:
- list visuals: **/report/pages/:pageName/visuals**
- get visual filters: **/report/pages/:pageName/visuals/:visualName/filters**

I also saw that IVisual doesn't have type property. Do you know if it is possible to find that information using Rest API? Or maybe you can give us a link to Rest API documentation?

**Comment by ali-hamud** [comment]
Hi @marcindabrowski 
These urls are not exposed yet in power bi service.
so, calling them will do nothing.

We are giving this feature high priority. but I cannot update on ETA right now.

**Comment by marcindabrowski** [comment]
Hi @ali-hamud.
I was thinking about getFilters on visuals and now I'm not sure is it that what I want.

I don't know how it will work on slicers. If I call getFilters on slicer visual will I receive values selected on slicer or values filtered in "Visual level filters"? 

I must say, that I prefer to get values selected on slicer.

I also tried to put some columns on the slicer, but it seems that it is not possible, so the option of returning selected values is reasonable behavior.

Could you confirm that?

**Comment by ali-hamud** [comment]
This feature is available now. closing the issue.

@marcindabrowski 
getFilters on slicers will give you the filters applied on this slicer and not the filters applied by the slicer.
We have a task to support slicers in javascript SDK, to give this task higher priority, please open an idea on https://ideas.powerbi.

**Comment by franmer** [comment]
Is getVisuals() available now?

**Comment by ali-hamud** [comment]
Yes

**Comment by ali-hamud** [comment]
You can also call: Get filters and Set filters on a specific visual:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Filters

And In addition, you can customize the visibility, position and size of each visual using Custom Layout:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Custom-Layout

**Comment by marcindabrowski** [comment]
And what about setting filters on slicers?
Currently in Power BI Desktop on those visuals we can't set visual level filters. So if I try to set visual level filter on slicer it will change it and new values will be selected on slicer?
