### ISSUE TITLE
Custom visual do not appear in power BI javascript api

### ISSUE THREAD

**Issue by soodik323** [Microsoft/PowerBI-JavaScript#76]
Hi

Seems, that custom visuals are not appearing in powerbi javascript api. I tried with Liquid Fill Gauge, Stars. Sometimes they do appear, but mostly not. Only title appears.

With builtin visuals, this problem does not occure(bar chart etc.)
PIC about the problem  -> http://picpaste.com/pics/javascriptApiError-VIu1FGt5.1477127571.PNG
Here you can repro this -> http://columbusbonusjavascript20160915051348.azurewebsites.net/

Code i use here is from javascript demo site.

**Comment by ali-hamud** [comment]
It's known issue I will update when we have a fix. Thank you

**Comment by joemensor** [comment]
Do we have an ETA on this fix?

**Comment by ali-hamud** [comment]
Estimation: 2-3 weeks.

**Comment by joefreddy** [comment]
This still doesn't work, you can reproduce using:
https://github.com/Microsoft/PowerBI-CSharp/tree/master/samples/webforms/embed-a-report-into-an-app
and a dummy pbix on powerbi.com that has a custom visual (e.g. http://okviz.com/candlestick/)

**Comment by sharonlai** [comment]
http://pbiecust.azurewebsites.net/
works for me

**Comment by joefreddy** [comment]
Could it be the source? The sample we used for reproducing uses powerbi.com as the source, and the above uses pbi embedded.

**Comment by soodik323** [comment]
Yeah, still does not work. i can still reproduce this. I also so powerbi.com
http://picpaste.com/CustomVisMissing-r6XQFD6A.PNG

**Comment by soodik323** [comment]
Any updates, Do we have an ETA on this fix?

**Comment by soodik323** [comment]
Seems , that this issue appear only when using powerbi.com,  When using azure, this problem does not appear.

**Comment by soodik323** [comment]
This is fixed
