### ISSUE TITLE
Wish: Callback for Filter changes

### ISSUE THREAD

**Issue by VitaliKaiser** [Microsoft/PowerBI-JavaScript#8]
If a the user changes a Filter settings (e.g. by clicking on a visual) it would be nice if you would get a event callback. Maybe you also could add a method to get all currently active filter of a report.

**Comment by wbreza** [comment]
@VitaliKaiser This is on our backlog and should be available when Power BI Embedded reaches general availability.

**Comment by szahn** [comment]
+1

**Comment by ali-hamud** [comment]
Hi all,
we add "Rendered" event.
you may listen on this event to know if something changed.

If user changes the current filter, your app will receive "rendered" event.
Then, you can call the getFilters to receive the new filters.

please try it on 2.2.6 and tell me if it helps

**Comment by ali-hamud** [comment]
OK I am closing this issue.
please let me know if it doesn't work for you or if you need more help.
