### ISSUE TITLE
Embed tile using Javascript Api

### ISSUE THREAD

**Issue by sheldonyss** [Microsoft/PowerBI-JavaScript#88]
Is this possible?

**Comment by ali-hamud** [comment]
Not yet.

**Comment by tringuyenminh92** [comment]
Is this possible now?

**Comment by noanu** [comment]
no, not yet. Are you trying to embed using your powerBI account?

**Comment by cruise-insights** [comment]
Embedding a tile is a necessary enhancement. Also . inclusion for Embedding Dashboards and making Power BI embedded mobile UX same as Power BI Mobile are of high value.

**Comment by shobman** [comment]
Will the tiles be filterable? In need to embed singlular tiles into various places in my app, but using context within my app I want to pass a filter parameter to the tile.

**Comment by Showlet** [comment]
Has this been implemented yet?

**Comment by ali-hamud** [comment]
Not yet. I will talk to the team to see if we give it higher priority. Thank you

**Comment by softgandhi** [comment]
We are also looking for the embedding Power BI tiles using javascript.
Request to provide further info on if this will get implemented soon.
Below is the article but doesn't seems to work (sample code uses iframe):
https://powerbi.microsoft.com/en-us/documentation/powerbi-developer-integrate-tile/

**Comment by ali-hamud** [comment]
Please read this wiki:
https://github.com/Microsoft/PowerBI-JavaScript/wiki/Tile-Embed

Please use this github as reference to embed a tile:
https://github.com/Microsoft/PowerBI-Developer-Samples/

Javascript code:
https://github.com/Microsoft/PowerBI-Developer-Samples/blob/master/App%20Owns%20Data/PowerBIEmbedded_AppOwnsData/Views/Home/EmbedTile.cshtml
