### ISSUE TITLE
Error in typings: Cannot find name 'Promise' when using Bluebird promise typings and targetting ES5

### ISSUE THREAD

**Issue by szahn** [Microsoft/PowerBI-JavaScript#92]
ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:15:50
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:25:63
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:26:75
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:27:74
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:28:76
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:29:78
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\http-post-message\dist\httpPostMessage.d.ts:30:70
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\powerbi-router\dist\router.d.ts:6:60
Cannot find name 'Promise'.

ERROR in [default] C:\...\node_modules\window-post-message-proxy\dist\windowPostMessageP
roxy.d.ts:77:56
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\embed.d.ts:124:88
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\embed.d.ts:169:14
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\ifilterable.d.ts:16:18
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\ifilterable.d.ts:23:43
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\ifilterable.d.ts:29:21
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\page.d.ts:60:18
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\page.d.ts:70:21
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\page.d.ts:80:17
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\page.d.ts:92:43
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:66:18
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:85:16
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:108:13
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:118:21
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:130:31
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:148:43
Cannot find name 'Promise'.

ERROR in [default] C:\...\typings\powerbi\report.d.ts:165:48
Cannot find name 'Promise'.

**Comment by ali-hamud** [comment]
did you included a promise library? like:
<script src="https://npmcdn.com/es6-promise@3.2.1"></script>

**Comment by szahn** [comment]
This error occurs during the webpack compilation. I'm using Bluebird promise library. Where would I put the script include tag?

**Comment by ali-hamud** [comment]
I am not familiar with Bluebird. did you find an answer?

**Comment by ali-hamud** [comment]
Closing the issue as no response.
please re-open if it's still relevant
