### ISSUE TITLE
reload & load functions don't refreshes data correctly (caching problem)

### ISSUE THREAD

**Issue by leszekrogowski** [Microsoft/PowerBI-JavaScript#96]
I have a SQL Server data source configured in Direct Query mode. When report is reloaded by using:

`embeddedReport.reload()`
or 
`embeddedReport.load(configuration)`

it doesn't fetch data source but from some Power BI cache. If you refresh the entire page (or iframe) it will correctly fetch the current data from SQL Server.

**Comment by t-val** [comment]
This relates to item [https://github.com/Microsoft/PowerBI-JavaScript/pull/85](url) which I commented on.  Sounds like we need to call .refresh() which was removed pending further investigation into its impact on billing with power bi embedded.

**Comment by leszekrogowski** [comment]
@t-val, thank you for your comment, and you're right. When, I'm manually posting /report/refresh, it correctly fetches data from database. I believe that that refresh functionality should be exposed in the library.
