### ISSUE TITLE
DataSelected event doesn't have values. only categories.

### ISSUE THREAD

**Issue by ali-hamud** [Microsoft/PowerBI-JavaScript#98]

**Comment by JohnKris** [comment]
According to [https://github.com/Microsoft/PowerBI-JavaScript/wiki/Handling-Events](url) the **values** array is "In Progress". Could you provide an indication when this will be fixed?

**Comment by noanu** [comment]
Hi,
This issue is on our task list, but it will take at least a few weeks until a fix gets to production.

When there are more updates - I will update here.

thanks for openinng the issue,

Noa

**Comment by zhll2046** [comment]
The same bug here, any ETA to fix it?

**Comment by noanu** [comment]
Hi,

We are aware of the importance of this issue and we are currently working on a fix for that. It will take at least a few weeks untill a fix gets to production, I will update here when we submit the fix - then we will be able to say pretty accuratly when it would get to production.

**Comment by zhll2046** [comment]
good day, any update there? I see someone saying that they used to see "see record","see data" when right click on a visual but now the right click don't pop up anything, does this bug related to the right click behavior?

**Comment by zhll2046** [comment]
http://community.powerbi.com/t5/forums/replypage/board-id/Developer/message-id/3967

**Comment by ali-hamud** [comment]
I don't think we ever had a context menu on Right click.
But we have a context menu for each visual. three points on the visual top right corner. if that what you need.

Data selected event is thrown when user selects a data point or multiple data point. and it's not related to right click.

I am closing this issue.
please feel free to ask any questions.
